<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Activity;

class ActivitySeeder extends Seeder
{
    public function run()
    {
        $activities = [
            [
                'activity_title' => 'Watch a Movie',
                'activity_type' => 'Movie',
                'venue_name' => 'TIFF Bell Lightbox',
                'description' => 'Premium cinema experience with latest blockbusters and indie films.',
                'address' => '350 King St W, Toronto, ON M5V 3X5',
                'latitude' => 43.6467,
                'longitude' => -79.3917,
                'budget_tag' => '$',
                'budget_display_text' => '$12-18',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Perfect for: Solo Movie Time',
                'estimated_duration_minutes' => 150,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://tiff.net/lightbox',
                'booking_url' => 'https://tiff.net/tickets',
            ],
            [
                'activity_title' => 'Romantic Movie Date',
                'activity_type' => 'Movie',
                'venue_name' => 'Cineplex VIP Cinemas',
                'description' => 'Premium cinema with reclining seats and in-theater dining',
                'address' => '10 Dundas St E, Toronto, ON M5B 2G9',
                'latitude' => 43.6563,
                'longitude' => -79.3799,
                'budget_tag' => '$$',
                'budget_display_text' => '$25-35',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Perfect for: Date Night',
                'estimated_duration_minutes' => 150,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.cineplex.com/theatres/cineplex-vip-cinemas-don-mills',
                'booking_url' => 'https://www.cineplex.com/showtimes',
            ],
            [
                'activity_title' => 'Art Gallery Visit',
                'activity_type' => 'Art',
                'venue_name' => 'Art Gallery of Ontario',
                'description' => 'World-class art collection featuring Canadian and international works.',
                'address' => '317 Dundas St W, Toronto, ON M5T 1G4',
                'latitude' => 43.6536,
                'longitude' => -79.3925,
                'budget_tag' => '$$',
                'budget_display_text' => '$15-25',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Great for: Culture Lovers',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://ago.ca',
                'booking_url' => 'https://ago.ca/tickets',
            ],
            [
                'activity_title' => 'Harbourfront Stroll',
                'activity_type' => 'Walking',
                'venue_name' => 'Harbourfront Centre',
                'description' => 'Scenic walk along Toronto\'s waterfront with city skyline views.',
                'address' => '235 Queens Quay W, Toronto, ON M5J 2G8',
                'latitude' => 43.6386,
                'longitude' => -79.3816,
                'budget_tag' => '$',
                'budget_display_text' => 'Free',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Great for: Group Walks',
                'estimated_duration_minutes' => 60,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Comfortable walking shoes',
                'website_url' => 'https://harbourfrontcentre.com',
            ],

            // MEDIUM ENERGY ACTIVITIES
            [
                'activity_title' => 'Go Bowling',
                'activity_type' => 'Bowling',
                'venue_name' => 'The Ballroom Bowl',
                'description' => 'Vintage bowling alley with a retro atmosphere, full bar and restaurant.',
                'address' => '1 Dupont St, Toronto, ON M5R 1V3',
                'latitude' => 43.6747,
                'longitude' => -79.4040,
                'budget_tag' => '$$',
                'budget_display_text' => '$25-40',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Fun for: Solo Practice',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None - shoes provided',
                'website_url' => 'https://theballroom.ca',
                'booking_url' => 'https://theballroom.ca/reservations',
            ],
            [
                'activity_title' => 'Comedy Show Date',
                'activity_type' => 'Comedy',
                'venue_name' => 'Second City Toronto',
                'description' => 'Live improv and sketch comedy performances.',
                'address' => '51 Mercer St, Toronto, ON M5V 1H2',
                'latitude' => 43.6447,
                'longitude' => -79.3932,
                'budget_tag' => '$$',
                'budget_display_text' => '$30-45',
                'energy_tag' => 'Medium',
                'people_tag' => 'Date',
                'people_display_text' => 'Fun for: Couples',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://secondcity.com/toronto',
                'booking_url' => 'https://secondcity.com/toronto/shows',
            ],
            [
                'activity_title' => 'Group Bowling',
                'activity_type' => 'Bowling',
                'venue_name' => 'Splitsville Entertainment',
                'description' => 'Modern bowling with food, drinks, and party atmosphere',
                'address' => '1485 Dundas St E, Mississauga, ON L4X 1L4',
                'latitude' => 43.6065,
                'longitude' => -79.6441,
                'budget_tag' => '$$',
                'budget_display_text' => '$30-50',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Perfect for: Friend Groups',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None - shoes provided',
                'website_url' => 'https://splitsville.com',
                'booking_url' => 'https://splitsville.com/reservations',
            ],
            [
                'activity_title' => 'Trivia Night',
                'activity_type' => 'Games',
                'venue_name' => 'The Rec Room',
                'description' => 'Entertainment complex with games, food, and trivia nights',
                'address' => '255 Bremner Blvd, Toronto, ON M5V 3M9',
                'latitude' => 43.6426,
                'longitude' => -79.3871,
                'budget_tag' => '$',
                'budget_display_text' => '$15-25',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Great for: Team Building',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.therecroom.com',
                'booking_url' => 'https://www.therecroom.com/locations/toronto',
            ],

            // HIGH ENERGY ACTIVITIES
            [
                'activity_title' => 'Escape Room Challenge',
                'activity_type' => 'Escape Room',
                'venue_name' => 'Casa Loma Escape Series',
                'description' => 'Immersive escape room experiences in a castle setting.',
                'address' => '1 Austin Terrace, Toronto, ON M5R 1X8',
                'latitude' => 43.6780,
                'longitude' => -79.4094,
                'budget_tag' => '$$$',
                'budget_display_text' => '$35-50',
                'energy_tag' => 'High',
                'people_tag' => 'Solo',
                'people_display_text' => 'Challenge for: Solo Adventurers',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://casaloma.ca/escape-series',
                'booking_url' => 'https://casaloma.ca/escape-series/book',
            ],
            [
                'activity_title' => 'Karaoke Night',
                'activity_type' => 'Karaoke',
                'venue_name' => 'Echo Karaoke & Lounge',
                'description' => 'Private karaoke rooms with extensive song selection.',
                'address' => '693 Bloor Street W Toronto, ON M6G 1L5',
                'latitude' => 43.6627,
                'longitude' => -79.4397,
                'budget_tag' => '$$',
                'budget_display_text' => '$30-50',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Fun for: Adventurous Couples',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.echokaraoke.ca/',
                'booking_url' => 'https://www.echokaraoke.ca/booking',
            ],
            [
                'activity_title' => 'Axe Throwing',
                'activity_type' => 'Sports',
                'venue_name' => 'BATL Axe Throwing',
                'description' => 'Urban axe throwing experience with coaching',
                'address' => '647 Queen St W, Toronto, ON M6J 1E4',
                'latitude' => 43.6467,
                'longitude' => -79.4141,
                'budget_tag' => '$$',
                'budget_display_text' => '$25-40',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Exciting for: Adventure Groups',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None - equipment provided',
                'website_url' => 'https://batlgrounds.com',
                'booking_url' => 'https://batlgrounds.com/locations/toronto-queen-west',
            ],
            [
                'activity_title' => 'Party Karaoke',
                'activity_type' => 'Karaoke',
                'venue_name' => 'Phoenix Concert Theatre',
                'description' => 'Large karaoke events and party nights',
                'address' => '410 Sherbourne St, Toronto, ON M4X 1K2',
                'latitude' => 43.6656,
                'longitude' => -79.3727,
                'budget_tag' => '$$$',
                'budget_display_text' => '$40-60',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Perfect for: Party Groups',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://phoenixconcerttheatre.com',
                'booking_url' => 'https://phoenixconcerttheatre.com/events',
            ],

            // ADDITIONAL BUDGET COVERAGE
            [
                'activity_title' => 'CN Tower EdgeWalk',
                'activity_type' => 'Adventure',
                'venue_name' => 'CN Tower',
                'description' => 'Walk around the outside of the CN Tower\'s main pod',
                'address' => '290 Bremner Blvd, Toronto, ON M5V 3L9',
                'latitude' => 43.6426,
                'longitude' => -79.3871,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$175-225',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Adventure for: Thrill Seekers',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Provided safety equipment',
                'website_url' => 'https://cntower.ca/edgewalk',
                'booking_url' => 'https://cntower.ca/edgewalk/tickets',
            ],
            [
                'activity_title' => 'Helicopter Tour',
                'activity_type' => 'Adventure',
                'venue_name' => 'National Helicopter',
                'description' => 'Luxury helicopter tour of Toronto skyline',
                'address' => 'Billy Bishop Airport, Toronto, ON M5V 1A1',
                'latitude' => 43.6275,
                'longitude' => -79.3963,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$300-500',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Ultimate for: Special Occasions',
                'estimated_duration_minutes' => 60,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Valid ID required',
                'website_url' => 'https://nationalhelicopters.com',
                'booking_url' => 'https://nationalhelicopters.com/tours',
            ],
            [
                'activity_title' => 'Board Game Café',
                'activity_type' => 'Games',
                'venue_name' => 'Snakes & Lattes',
                'description' => 'Board game cafe with hundreds of games to choose from',
                'address' => '600 Bloor St W, Toronto, ON M6G 1K4',
                'latitude' => 43.6634,
                'longitude' => -79.4108,
                'budget_tag' => '$',
                'budget_display_text' => '$10-20',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Perfect for: Casual Dates',
                'estimated_duration_minutes' => 150,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None - games provided',
                'website_url' => 'https://snakesandlattes.com',
            ],

            // FILLING ALL COMBINATIONS - ACTIVITIES
            // LOW ENERGY
            [
                'activity_title' => 'Quiet Library Reading',
                'activity_type' => 'Reading',
                'venue_name' => 'Toronto Reference Library',
                'description' => 'Spend a peaceful afternoon reading in a grand library.',
                'address' => '789 Yonge St, Toronto, ON M4W 2G8',
                'latitude' => 43.6706,
                'longitude' => -79.3879,
                'budget_tag' => '$',
                'budget_display_text' => 'Free',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Peaceful for: Solo Reading',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.torontopubliclibrary.ca/trl/',
            ],
            [
                'activity_title' => 'Park Picnic',
                'activity_type' => 'Outdoor',
                'venue_name' => 'High Park',
                'description' => 'Relaxing picnic in Toronto\'s largest public park.',
                'address' => '1873 Bloor St W, Toronto, ON M6R 2Z3',
                'latitude' => 43.6558,
                'longitude' => -79.4639,
                'budget_tag' => '$$',
                'budget_display_text' => '$30-50',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Perfect for: Romantic Picnics',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Picnic basket, blanket',
                'website_url' => 'https://www.highparktoronto.com',
            ],
            [
                'activity_title' => 'Distillery District Exploration',
                'activity_type' => 'Walking',
                'venue_name' => 'The Distillery District',
                'description' => 'Stroll through historic Victorian-era buildings, shops, and cafes.',
                'address' => '55 Mill St, Toronto, ON M5A 3C4',
                'latitude' => 43.6504,
                'longitude' => -79.3582,
                'budget_tag' => '$$$',
                'budget_display_text' => '$40-80 (incl. shopping/food)',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Ideal for: Friends Exploring',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Comfortable shoes',
                'website_url' => 'https://www.thedistillerydistrict.com',
            ],
            [
                'activity_title' => 'Spa Day Relaxation',
                'activity_type' => 'Wellness',
                'venue_name' => 'Elmwood Spa',
                'description' => 'Unwind with a luxurious spa treatment and relaxation.',
                'address' => '18 Elm St, Toronto, ON M5G 1G7',
                'latitude' => 43.6575,
                'longitude' => -79.3831,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$100-200',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Relaxing for: Couples Retreat',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Swimsuit (optional)',
                'website_url' => 'https://www.elmwoodspa.com',
                'booking_url' => 'https://www.elmwoodspa.com/packages/',
            ],
            [
                'activity_title' => 'Private Yacht Charter',
                'activity_type' => 'Boating',
                'venue_name' => 'Toronto Harbour Yachts',
                'description' => 'Exclusive private yacht experience on Lake Ontario.',
                'address' => 'Various Marinas, Toronto',
                'latitude' => 43.6386, // Representative
                'longitude' => -79.3816, // Representative
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$1000-2000',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Ultimate for: Luxury Gatherings',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.torontoyachtrentals.ca/',
                'booking_url' => 'https://www.torontoyachtrentals.ca/contact/',
            ],
            [
                'activity_title' => 'Quiet Art Class',
                'activity_type' => 'Art',
                'venue_name' => 'Art Works Art School',
                'description' => 'Beginner-friendly art class for relaxation and creativity.',
                'address' => '657 Yonge St, Toronto, ON M4Y 1Z9',
                'latitude' => 43.6669,
                'longitude' => -79.3877,
                'budget_tag' => '$$',
                'budget_display_text' => '$50-75',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Relaxing for: Solo Creativity',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None - materials provided',
                'website_url' => 'https://artworksto.ca/',
                'booking_url' => 'https://artworksto.ca/adult-classes/',
            ],
            [
                'activity_title' => 'High-Tea Experience',
                'activity_type' => 'Dining',
                'venue_name' => 'The King Edward Hotel',
                'description' => 'Elegant high tea with pastries and sandwiches.',
                'address' => '37 King St E, Toronto, ON M5C 1E9',
                'latitude' => 43.6508,
                'longitude' => -79.3758,
                'budget_tag' => '$$$',
                'budget_display_text' => '$60-90',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Charming for: Elegant Dates',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Smart casual attire',
                'website_url' => 'https://www.omnihotels.com/hotels/toronto-king-edward/dining/afternoon-tea',
                'booking_url' => 'https://www.opentable.ca/r/the-library-bar-at-the-omni-king-edward-hotel-toronto',
            ],
            [
                'activity_title' => 'Botanical Garden Visit',
                'activity_type' => 'Nature',
                'venue_name' => 'Toronto Botanical Garden',
                'description' => 'Peaceful walk through beautifully curated gardens.',
                'address' => '777 Lawrence Ave E, Toronto, ON M3C 1P2',
                'latitude' => 43.7226,
                'longitude' => -79.3512,
                'budget_tag' => '$',
                'budget_display_text' => 'Free',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Calm for: Small Group Outings',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'None',
                'website_url' => 'https://torontobotanicalgarden.ca/',
            ],
            [
                'activity_title' => 'Private Chef Dining Experience',
                'activity_type' => 'Dining',
                'venue_name' => 'In-Home Experience',
                'description' => 'Enjoy a gourmet meal prepared by a private chef in your home.',
                'address' => 'Your Location, Toronto', // Placeholder
                'latitude' => 43.6532,
                'longitude' => -79.3832,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$500-1000+',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Exclusive for: Intimate Gatherings',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Kitchen access',
                'website_url' => 'https://www.hireacheftoronto.com/', // Example service
            ],
            [
                'activity_title' => 'Luxury Private Tour (Museums)',
                'activity_type' => 'Culture',
                'venue_name' => 'Various Museums (ROM, AGO)',
                'description' => 'Curated private tour of Toronto\'s top museums with expert guide.',
                'address' => 'Various, Toronto',
                'latitude' => 43.6532,
                'longitude' => -79.3832,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$300-600',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Enriching for: High-End Groups',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.luxurylifetours.com/toronto-private-tours', // Example
                'booking_url' => 'https://www.luxurylifetours.com/contact-us',
            ],
            [
                'activity_title' => 'Exclusive Wine Tasting',
                'activity_type' => 'Wine Tasting',
                'venue_name' => 'Sommellerie Ontario',
                'description' => 'Private tasting of rare wines with a professional sommelier.',
                'address' => 'Discreet Location, Toronto',
                'latitude' => 43.6532,
                'longitude' => -79.3832,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$500-1500',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Refined for: Connoisseurs',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://sommellerie.ca/',
                'booking_url' => 'https://sommellerie.ca/contact/',
            ],
            [
                'activity_title' => 'Luxury Spa & Retreat',
                'activity_type' => 'Wellness',
                'venue_name' => 'Miraj Hammam Spa by Caudalie Paris',
                'description' => 'Indulge in exclusive Middle Eastern-inspired spa treatments.',
                'address' => '181 Bay St, Toronto, ON M5J 2T3',
                'latitude' => 43.6473,
                'longitude' => -79.3791,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$300-700',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Opulent for: Romantic Escapes',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.mirajhammam.com/',
                'booking_url' => 'https://www.mirajhammam.com/contact/',
            ],
            [
                'activity_title' => 'Exclusive Shopping Spree',
                'activity_type' => 'Shopping',
                'venue_name' => 'Bloor Street West Boutiques',
                'description' => 'Personalized shopping experience with a stylist at luxury boutiques.',
                'address' => 'Bloor St W, Toronto, ON',
                'latitude' => 43.6685,
                'longitude' => -79.3951,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$1000+',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Luxurious for: High-End Shoppers',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Credit card',
                'website_url' => 'https://bloorstreetwest.ca/',
            ],

            // MEDIUM ENERGY
            [
                'activity_title' => 'Indoor Rock Climbing',
                'activity_type' => 'Sports',
                'venue_name' => 'Climber\'s Rock',
                'description' => 'Challenging routes for all skill levels at a modern climbing gym.',
                'address' => '2700 Dufferin St, Toronto, ON M6B 4J3',
                'latitude' => 43.6937,
                'longitude' => -79.4475,
                'budget_tag' => '$$',
                'budget_display_text' => '$25-45',
                'energy_tag' => 'Medium',
                'people_tag' => 'Date',
                'people_display_text' => 'Active for: Adventurous Dates',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Comfortable clothing',
                'website_url' => 'https://climbersrock.com',
                'booking_url' => 'https://climbersrock.com/toronto/',
            ],
            [
                'activity_title' => 'Cooking Class',
                'activity_type' => 'Cooking',
                'venue_name' => 'Dish Cooking Studio',
                'description' => 'Hands-on cooking class with a professional chef.',
                'address' => '390 College St, Toronto, ON M5T 1S6',
                'latitude' => 43.6552,
                'longitude' => -79.4000,
                'budget_tag' => '$$$',
                'budget_display_text' => '$75-125',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Engaging for: Solo Learning',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://dishcookingstudio.com',
                'booking_url' => 'https://dishcookingstudio.com/classes/',
            ],
            [
                'activity_title' => 'VR Arcade Experience',
                'activity_type' => 'Gaming',
                'venue_name' => 'Levelup Virtual Reality Arcade',
                'description' => 'Immersive virtual reality gaming experience for all ages.',
                'address' => '130 Eglinton Ave E, Toronto, ON M4P 2X9',
                'latitude' => 43.7088,
                'longitude' => -79.3995,
                'budget_tag' => '$$',
                'budget_display_text' => '$30-60',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Exciting for: Small Group Fun',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://levelupvr.ca/',
                'booking_url' => 'https://levelupvr.ca/booking',
            ],
            [
                'activity_title' => 'Trampoline Park',
                'activity_type' => 'Recreation',
                'venue_name' => 'Sky Zone Trampoline Park',
                'description' => 'Jump, flip, and soar at this indoor trampoline park.',
                'address' => '1000 Gerrard St E, Toronto, ON M4M 3G6',
                'latitude' => 43.6672,
                'longitude' => -79.3499,
                'budget_tag' => '$',
                'budget_display_text' => '$20-30',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Energetic for: Energetic Groups',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Socks',
                'website_url' => 'https://www.skyzone.com/toronto',
                'booking_url' => 'https://www.skyzone.com/toronto/tickets-waivers',
            ],
            [
                'activity_title' => 'Concert at Massey Hall',
                'activity_type' => 'Music',
                'venue_name' => 'Massey Hall',
                'description' => 'Experience live music in a historic and acoustically renowned venue.',
                'address' => '178 Victoria St, Toronto, ON M5B 1T7',
                'latitude' => 43.6552,
                'longitude' => -79.3791,
                'budget_tag' => '$$$',
                'budget_display_text' => '$50-100+',
                'energy_tag' => 'Medium',
                'people_tag' => 'Date',
                'people_display_text' => 'Cultural for: Music Lovers',
                'estimated_duration_minutes' => 150,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://masseyhall.com',
                'booking_url' => 'https://masseyhall.com/tickets/',
            ],
            [
                'activity_title' => 'Interactive Museum Visit',
                'activity_type' => 'Museum',
                'venue_name' => 'Ontario Science Centre',
                'description' => 'Engaging and hands-on exhibits for all ages.',
                'address' => '770 Don Mills Rd, North York, ON M3C 1T3',
                'latitude' => 43.7161,
                'longitude' => -79.3382,
                'budget_tag' => '$$',
                'budget_display_text' => '$20-30',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Educational for: Group Learning',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.ontariosciencecentre.ca',
                'booking_url' => 'https://www.ontariosciencecentre.ca/tickets',
            ],
            [
                'activity_title' => 'Arcade Bar Night',
                'activity_type' => 'Games',
                'venue_name' => 'Tilt Arcade Bar',
                'description' => 'Retro arcade games, pinball, and craft beer in a lively setting.',
                'address' => '298 College St, Toronto, ON M5T 1S4',
                'latitude' => 43.6563,
                'longitude' => -79.3995,
                'budget_tag' => '$$',
                'budget_display_text' => '$20-40',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Lively for: Group Fun',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.tilttoronto.com/',
            ],
            [
                'activity_title' => 'Kayaking on Lake Ontario',
                'activity_type' => 'Water Sports',
                'venue_name' => 'Toronto Island SUP & Kayak',
                'description' => 'Rent kayaks and explore the Toronto Islands waterways.',
                'address' => 'Centre Island, Toronto, ON',
                'latitude' => 43.6212,
                'longitude' => -79.3789,
                'budget_tag' => '$$$',
                'budget_display_text' => '$40-70',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Active for: Outdoor Enthusiasts',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Swimsuit (optional), sunscreen',
                'website_url' => 'https://torontoislandsup.com/',
                'booking_url' => 'https://torontoislandsup.com/rentals/',
            ],
            [
                'activity_title' => 'Indoor Mini Golf',
                'activity_type' => 'Mini Golf',
                'venue_name' => 'Par-Tee Putt',
                'description' => 'Unique themed indoor mini golf courses with a bar.',
                'address' => '26 Duncan St, Toronto, ON M5V 2B9',
                'latitude' => 43.6473,
                'longitude' => -79.3907,
                'budget_tag' => '$$',
                'budget_display_text' => '$20-35',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Casual for: Solo Practice',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.parteeputt.com/',
                'booking_url' => 'https://www.parteeputt.com/book-now/',
            ],
            [
                'activity_title' => 'Wine Tour in Niagara-on-the-Lake',
                'activity_type' => 'Wine Tour',
                'venue_name' => 'Various Wineries',
                'description' => 'Guided tour of beautiful wineries with tastings in Niagara-on-the-Lake.',
                'address' => 'Niagara-on-the-Lake, ON (Day Trip from Toronto)',
                'latitude' => 43.2559,
                'longitude' => -79.0763,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$150-300',
                'energy_tag' => 'Medium',
                'people_tag' => 'Date',
                'people_display_text' => 'Romantic for: Wine Enthusiasts',
                'estimated_duration_minutes' => 360,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.niagarawinetours.com/',
                'booking_url' => 'https://www.niagarawinetours.com/book-now/',
            ],
            [
                'activity_title' => 'Luxury Cooking Class',
                'activity_type' => 'Cooking',
                'venue_name' => 'Presidential Suite Kitchen (Hotel)',
                'description' => 'Exclusive cooking class with a renowned chef in a luxurious setting.',
                'address' => 'Hotel X Toronto, 111 Princes Blvd, Toronto, ON M6K 3C3',
                'latitude' => 43.6378,
                'longitude' => -79.4172,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$400-800',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Exclusive for: Culinary Enthusiasts',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://hotelxtoronto.com/', // Example - likely bespoke
            ],
            [
                'activity_title' => 'Team Building Escape Rooms',
                'activity_type' => 'Escape Room',
                'venue_name' => 'Escapology Toronto',
                'description' => 'Challenging and engaging escape rooms designed for large groups.',
                'address' => '181 Bay St, Toronto, ON M5J 2T3',
                'latitude' => 43.6473,
                'longitude' => -79.3791,
                'budget_tag' => '$$$',
                'budget_display_text' => '$40-60',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Engaging for: Large Group Challenges',
                'estimated_duration_minutes' => 90,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://escapology.com/toronto/',
                'booking_url' => 'https://escapology.com/toronto/book/',
            ],
            [
                'activity_title' => 'VIP Sporting Event',
                'activity_type' => 'Sports',
                'venue_name' => 'Scotiabank Arena',
                'description' => 'Experience a Raptors or Maple Leafs game from a luxury suite.',
                'address' => '40 Bay St, Toronto, ON M5J 2L2',
                'latitude' => 43.6434,
                'longitude' => -79.3791,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$500-2000+',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Premium for: Corporate & Large Groups',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.scotiabankarena.com/',
                'booking_url' => 'https://www.scotiabankarena.com/luxury-suites/',
            ],
            [
                'activity_title' => 'Premium Concert Experience',
                'activity_type' => 'Music',
                'venue_name' => 'Budweiser Stage VIP',
                'description' => 'Enjoy a concert with premium seating and hospitality.',
                'address' => '909 Lake Shore Blvd W, Toronto, ON M5V 3L9',
                'latitude' => 43.6335,
                'longitude' => -79.4087,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$150-400',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Memorable for: Music Lovers',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.livenation.com/venues/14467/budweiser-stage',
                'booking_url' => 'https://www.ticketmaster.ca/',
            ],

            // HIGH ENERGY
            [
                'activity_title' => 'Paintball Warzone',
                'activity_type' => 'Action Sports',
                'venue_name' => 'Paintball City',
                'description' => 'Fast-paced paintball action on various themed fields.',
                'address' => '2501 Steeles Ave W, North York, ON M3J 2P1',
                'latitude' => 43.7845,
                'longitude' => -79.4674,
                'budget_tag' => '$$$',
                'budget_display_text' => '$50-80',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Intense for: Action Seekers',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Comfortable clothing',
                'website_url' => 'https://paintballcity.ca/',
                'booking_url' => 'https://paintballcity.ca/reservations/',
            ],
            [
                'activity_title' => 'Indoor Skydiving',
                'activity_type' => 'Adventure',
                'venue_name' => 'iFLY Toronto',
                'description' => 'Experience the thrill of skydiving in a safe indoor wind tunnel.',
                'address' => '2007 Winston Park Dr, Oakville, ON L6H 6P5',
                'latitude' => 43.5186,
                'longitude' => -79.7431,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$80-150',
                'energy_tag' => 'High',
                'people_tag' => 'Solo',
                'people_display_text' => 'Thrilling for: Solo Adventurers',
                'estimated_duration_minutes' => 60,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Comfortable clothing',
                'website_url' => 'https://www.iflytoronto.com/',
                'booking_url' => 'https://www.iflytoronto.com/book-now/',
            ],
            [
                'activity_title' => 'Go-Kart Racing',
                'activity_type' => 'Racing',
                'venue_name' => 'K1 Speed Toronto',
                'description' => 'Indoor electric go-kart racing for adrenaline junkies.',
                'address' => '75 Carl Hall Rd, Toronto, ON M3K 2B9',
                'latitude' => 43.7600,
                'longitude' => -79.4795,
                'budget_tag' => '$$',
                'budget_display_text' => '$30-50',
                'energy_tag' => 'High',
                'people_tag' => 'Solo',
                'people_display_text' => 'Fast for: Solo Racers',
                'estimated_duration_minutes' => 60,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Closed-toe shoes',
                'website_url' => 'https://www.k1speed.ca/toronto-location.html',
                'booking_url' => 'https://www.k1speed.ca/toronto-location.html',
            ],
            [
                'activity_title' => 'Hot Air Balloon Ride',
                'activity_type' => 'Adventure',
                'venue_name' => 'Sundance Balloons',
                'description' => 'Scenic hot air balloon ride over the Ontario countryside.',
                'address' => 'Various launch sites near Toronto',
                'latitude' => 43.8, // Representative
                'longitude' => -79.5, // Representative
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$300-600',
                'energy_tag' => 'High',
                'people_tag' => 'Solo',
                'people_display_text' => 'Breathtaking for: Solo Views',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'None',
                'website_url' => 'https://sundanceballoons.com/',
                'booking_url' => 'https://sundanceballoons.com/book-a-flight/',
            ],
            [
                'activity_title' => 'Concert Mosh Pit',
                'activity_type' => 'Music',
                'venue_name' => 'Opera House',
                'description' => 'High-energy live music experience at a popular venue.',
                'address' => '735 Queen St E, Toronto, ON M4M 1H1',
                'latitude' => 43.6599,
                'longitude' => -79.3499,
                'budget_tag' => '$$',
                'budget_display_text' => '$30-60',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Intense for: Concert Goers',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://theoperahouse.ca/',
                'booking_url' => 'https://theoperahouse.ca/tickets/',
            ],
            [
                'activity_title' => 'Laser Tag Battle',
                'activity_type' => 'Games',
                'venue_name' => 'Laser Quest Toronto West',
                'description' => 'High-octane laser tag games in a multi-level arena.',
                'address' => '1000 Finch Ave W, North York, ON M3J 2V5',
                'latitude' => 43.7749,
                'longitude' => -79.4795,
                'budget_tag' => '$',
                'budget_display_text' => '$15-25',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Fun for: Competitive Friends',
                'estimated_duration_minutes' => 60,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://laserquest.com/locations/toronto-west/',
                'booking_url' => 'https://laserquest.com/locations/toronto-west/booking/',
            ],
            [
                'activity_title' => 'White Water Rafting',
                'activity_type' => 'Adventure',
                'venue_name' => 'Madawaska Kanu Centre',
                'description' => 'Exciting whitewater rafting adventure on the Madawaska River.',
                'address' => 'Palmer Rapids, ON (Day Trip from Toronto)',
                'latitude' => 45.3857,
                'longitude' => -77.3090,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$100-250',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Thrilling for: Group Adventures',
                'estimated_duration_minutes' => 480,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Swimsuit, towel',
                'website_url' => 'https://mkc.ca/',
                'booking_url' => 'https://mkc.ca/white-water-rafting-trips/',
            ],
            [
                'activity_title' => 'Rock Climbing Adventure (Outdoor)',
                'activity_type' => 'Outdoor Sports',
                'venue_name' => 'Rattlesnake Point Conservation Area',
                'description' => 'Outdoor rock climbing with stunning views (guided tours available).',
                'address' => '7207 Appleby Line, Milton, ON L9T 2X7',
                'latitude' => 43.4842,
                'longitude' => -79.9272,
                'budget_tag' => '$$$',
                'budget_display_text' => '$75-150',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Challenging for: Active Couples',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Appropriate footwear',
                'website_url' => 'https://www.conservationhalton.ca/locations/rattlesnake-point/',
                'booking_url' => 'https://www.zenithrock.com/programs', // Example guide service
            ],
            [
                'activity_title' => 'Nightclub Dancing',
                'activity_type' => 'Nightlife',
                'venue_name' => 'Rebel Nightclub',
                'description' => 'High-energy nightclub with top DJs and large dance floors.',
                'address' => '11 Polson St, Toronto, ON M5A 1A4',
                'latitude' => 43.6425,
                'longitude' => -79.3510,
                'budget_tag' => '$$$',
                'budget_display_text' => '$40-80 (incl. drinks)',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Vibrant for: Party Groups',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'ID, stylish attire',
                'website_url' => 'https://rebeltoronto.com/',
            ],
            [
                'activity_title' => 'Professional Sports Game (Premium Seats)',
                'activity_type' => 'Sports',
                'venue_name' => 'Rogers Centre',
                'description' => 'Watch a Blue Jays game from premium seating with concierge service.',
                'address' => '1 Blue Jays Way, Toronto, ON M5V 1J1',
                'latitude' => 43.6414,
                'longitude' => -79.3894,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$100-300',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Exciting for: Sports Fan Dates',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://www.mlb.com/bluejays/ballpark/premium-seating',
                'booking_url' => 'https://www.ticketmaster.ca/toronto-blue-jays-tickets/artist/806161',
            ],
            [
                'activity_title' => 'Luxury Private Jet Tour',
                'activity_type' => 'Adventure',
                'venue_name' => 'Private Air Charters',
                'description' => 'Exclusive private jet tour of the region with a personalized itinerary.',
                'address' => 'Pearson International Airport (YYZ)',
                'latitude' => 43.6777,
                'longitude' => -79.6248,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$2000-5000+',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Ultimate for: Extravagant Couples',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Valid ID',
                'website_url' => 'https://www.airchartercanada.ca/', // Example
                'booking_url' => 'https://www.airchartercanada.ca/contact-us/',
            ],
            [
                'activity_title' => 'Private Guided Hike (Challenging)',
                'activity_type' => 'Hiking',
                'venue_name' => 'Bruce Trail (guided section)',
                'description' => 'Challenging private guided hike through rugged terrain with scenic views.',
                'address' => 'Various points along the Bruce Trail (e.g., Mono Cliffs)',
                'latitude' => 43.9922,
                'longitude' => -80.0544,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$100-250',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Demanding for: Outdoor Enthusiasts',
                'estimated_duration_minutes' => 300,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Sturdy hiking boots, water, snacks',
                'website_url' => 'https://brucetrail.org/',
                'booking_url' => 'https://www.adventuretourism.ca/hiking-tours/', // Example guide
            ],
            [
                'activity_title' => 'Exclusive Nightclub VIP Experience',
                'activity_type' => 'Nightlife',
                'venue_name' => 'TOYBOX Nightclub',
                'description' => 'Book the entire VIP section with bottle service, private DJ, and premium entertainment for your group.',
                'address' => '471 Adelaide St W, Toronto, ON M5V 1T1',
                'latitude' => 43.6465,
                'longitude' => -79.3943,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$2000-5000',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Epic for: Group Celebrations',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Dress code required',
                'website_url' => 'https://toyboxto.com/',
                'booking_url' => 'https://toyboxto.com/vip-bookings/',
            ],
            
            [
                'activity_title' => 'Private Concert Hall Rental',
                'activity_type' => 'Entertainment',
                'venue_name' => 'Roy Thomson Hall',
                'description' => 'Book an entire concert hall for your large group with world-class performers and catering.',
                'address' => '60 Simcoe St, Toronto, ON M5J 2H5',
                'latitude' => 43.6465,
                'longitude' => -79.3871,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$5000-15000',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Spectacular for: Corporate Events',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://roythomsonhall.com/',
                'booking_url' => 'https://roythomsonhall.com/plan-your-event/',
            ],
            
            [
                'activity_title' => 'Luxury Yacht Party Charter',
                'activity_type' => 'Adventure',
                'venue_name' => 'Harbourfront Marina',
                'description' => 'Charter a luxury yacht with DJ, catering, and premium bar for the ultimate group celebration on Lake Ontario.',
                'address' => '235 Queens Quay W, Toronto, ON M5J 2G8',
                'latitude' => 43.6386,
                'longitude' => -79.3816,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$3000-8000',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Ultimate for: VIP Group Parties',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'Party attire',
                'website_url' => 'https://torontoyachtcharters.com/',
                'booking_url' => 'https://torontoyachtcharters.com/luxury-charters/',
            ],
            
            // Medium Energy + $$$$$ + Large Group
            [
                'activity_title' => 'Private Wine Estate Experience',
                'activity_type' => 'Food & Wine',
                'venue_name' => 'Niagara Wine Estate',
                'description' => 'Exclusive wine tasting with sommelier, private chef, and luxury transportation for your group.',
                'address' => 'Niagara-on-the-Lake, ON (Transport Included)',
                'latitude' => 43.2559,
                'longitude' => -79.0763,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$1500-4000',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Sophisticated for: Corporate Retreats',
                'estimated_duration_minutes' => 360,
                'indoor_outdoor_status' => 'Both',
                'required_materials' => 'None',
                'website_url' => 'https://niagarawinetours.com/',
                'booking_url' => 'https://niagarawinetours.com/private-groups/',
            ],
            
            [
                'activity_title' => 'Exclusive Culinary Masterclass',
                'activity_type' => 'Cooking',
                'venue_name' => 'Private Chef Studio',
                'description' => 'Learn from a Michelin-starred chef in an exclusive cooking class with wine pairings for your group.',
                'address' => 'King St W, Toronto, ON (Private Location)',
                'latitude' => 43.6426,
                'longitude' => -79.3871,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$2000-5000',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Gourmet for: Food Enthusiasts',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Aprons provided',
                'website_url' => 'https://torontoprivatechef.com/',
            ],
            
            // Low Energy + $$$$$ + Large Group
            [
                'activity_title' => 'Private Museum After-Hours Tour',
                'activity_type' => 'Culture',
                'venue_name' => 'Royal Ontario Museum',
                'description' => 'Exclusive after-hours private tour of the ROM with personal curator and champagne reception.',
                'address' => '100 Queens Park, Toronto, ON M5S 2C6',
                'latitude' => 43.6677,
                'longitude' => -79.3948,
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$3000-7000',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Exclusive for: Cultural Groups',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://rom.on.ca/',
                'booking_url' => 'https://rom.on.ca/en/plan-your-visit/group-visits',
            ],
            
            // High Energy + $$$$ + Large Group
            [
                'activity_title' => 'Escape Room Tournament',
                'activity_type' => 'Games',
                'venue_name' => 'Multiple Escape Room Venues',
                'description' => 'Organize a competitive escape room tournament across multiple venues with prizes and celebration.',
                'address' => 'Various Locations, Toronto, ON',
                'latitude' => 43.6532,
                'longitude' => -79.3832,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$500-1200',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Competitive for: Team Building',
                'estimated_duration_minutes' => 240,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Comfortable clothing',
                'website_url' => 'https://escapegames.ca/',
                'booking_url' => 'https://escapegames.ca/corporate-events/',
            ],
            
            [
                'activity_title' => 'Private Paintball Arena',
                'activity_type' => 'Sports',
                'venue_name' => 'Flag Raiders Paintball',
                'description' => 'Book an entire paintball facility for your group with equipment, refs, and celebration package.',
                'address' => '2501 Steeles Ave W, North York, ON M3J 2P1',
                'latitude' => 43.7845,
                'longitude' => -79.4674,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$800-1500',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Action-packed for: Adventure Groups',
                'estimated_duration_minutes' => 180,
                'indoor_outdoor_status' => 'Outdoor',
                'required_materials' => 'All equipment provided',
                'website_url' => 'https://flagraiders.com/',
                'booking_url' => 'https://flagraiders.com/group-bookings/',
            ],
            
            // Medium Energy + $$$$ + Large Group
            [
                'activity_title' => 'Private Brewery Tour & Tasting',
                'activity_type' => 'Food & Drink',
                'venue_name' => 'Steam Whistle Brewing',
                'description' => 'Exclusive brewery tour with beer tastings, food pairings, and private event space for your group.',
                'address' => '255 Bremner Blvd, Toronto, ON M5V 3M9',
                'latitude' => 43.6426,
                'longitude' => -79.3871,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$600-1200',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Social for: Beer Enthusiasts',
                'estimated_duration_minutes' => 150,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'None',
                'website_url' => 'https://steamwhistle.ca/',
                'booking_url' => 'https://steamwhistle.ca/tours/',
            ],
            
            // Low Energy + $$$$ + Large Group
            [
                'activity_title' => 'Luxury Spa Group Retreat',
                'activity_type' => 'Wellness',
                'venue_name' => 'Scandinavian Spa Blue Mountain',
                'description' => 'Full-day spa retreat with thermal waters, massages, and healthy gourmet lunch for your group.',
                'address' => 'Blue Mountain Resort, ON (Transport Available)',
                'latitude' => 44.5020,
                'longitude' => -80.2889,
                'budget_tag' => '$$$$',
                'budget_display_text' => '$800-1500',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Relaxing for: Wellness Groups',
                'estimated_duration_minutes' => 480,
                'indoor_outdoor_status' => 'Both',
                'required_materials' => 'Swimsuit, towel',
                'website_url' => 'https://scandispa.ca/',
                'booking_url' => 'https://scandispa.ca/group-packages/',
            ],
            
            // High Energy + $$$ + Large Group
            [
                'activity_title' => 'Group Axe Throwing Tournament',
                'activity_type' => 'Sports',
                'venue_name' => 'BATL Axe Throwing',
                'description' => 'Competitive axe throwing tournament with coaching, prizes, and group celebration area.',
                'address' => '647 Queen St W, Toronto, ON M6J 1E4',
                'latitude' => 43.6467,
                'longitude' => -79.4141,
                'budget_tag' => '$$$',
                'budget_display_text' => '$300-600',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Exciting for: Competitive Groups',
                'estimated_duration_minutes' => 120,
                'indoor_outdoor_status' => 'Indoor',
                'required_materials' => 'Closed-toe shoes',
                'website_url' => 'https://batlgrounds.com/',
                'booking_url' => 'https://batlgrounds.com/group-events/',
            ],
            // LOW ENERGY MISSING COMBINATIONS

// Low-$$$$-Solo
[
    'activity_title' => 'Private Museum Tour with Personal Curator',
    'activity_type' => 'Culture',
    'venue_name' => 'Royal Ontario Museum',
    'description' => 'Exclusive one-on-one museum tour with personal curator and behind-the-scenes access.',
    'address' => '100 Queens Park, Toronto, ON M5S 2C6',
    'latitude' => 43.6677,
    'longitude' => -79.3948,
    'budget_tag' => '$$$$',
    'budget_display_text' => '$200-300',
    'energy_tag' => 'Low',
    'people_tag' => 'Solo',
    'people_display_text' => 'Exclusive for: Solo Culture Enthusiasts',
    'estimated_duration_minutes' => 180,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'None',
    'website_url' => 'https://rom.on.ca/',
    'booking_url' => 'https://rom.on.ca/private-tours/',
],

// Low-$$$$$-Solo
[
    'activity_title' => 'Private Jet Wine Country Tour',
    'activity_type' => 'Luxury Travel',
    'venue_name' => 'Pearson Private Terminal',
    'description' => 'Solo luxury day trip to Niagara wine country by private jet with personal sommelier.',
    'address' => 'Pearson International Airport, ON',
    'latitude' => 43.6777,
    'longitude' => -79.6248,
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$2000-3500',
    'energy_tag' => 'Low',
    'people_tag' => 'Solo',
    'people_display_text' => 'Luxurious for: Solo Wine Connoisseurs',
    'estimated_duration_minutes' => 480,
    'indoor_outdoor_status' => 'Both',
    'required_materials' => 'Valid ID',
    'website_url' => 'https://privatemjet.ca/',
    'booking_url' => 'https://privatejet.ca/wine-tours/',
],

// Low-$$$$-Date
[
    'activity_title' => 'Couples Spa Retreat at Miraj Hammam',
    'activity_type' => 'Wellness',
    'venue_name' => 'Miraj Hammam Spa',
    'description' => 'Luxurious couples spa experience with traditional Hammam treatments and private relaxation suite.',
    'address' => '188 University Ave, Toronto, ON M5H 0A3',
    'latitude' => 43.6499,
    'longitude' => -79.3888,
    'budget_tag' => '$$$$',
    'budget_display_text' => '$400-600',
    'energy_tag' => 'Low',
    'people_tag' => 'Date',
    'people_display_text' => 'Luxurious for: Romantic Spa Retreats',
    'estimated_duration_minutes' => 240,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Swimsuit',
    'website_url' => 'https://www.mirajhammam.com/',
    'booking_url' => 'https://www.mirajhammam.com/couples-packages/',
],

// Low-$$$$$-Date
[
    'activity_title' => 'Private Island Picnic by Helicopter',
    'activity_type' => 'Luxury Adventure',
    'venue_name' => 'Toronto Islands Private Area',
    'description' => 'Helicopter transport to secluded island area with gourmet picnic setup and private butler service.',
    'address' => 'Billy Bishop Airport, Toronto, ON',
    'latitude' => 43.6275,
    'longitude' => -79.3963,
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$3000-5000',
    'energy_tag' => 'Low',
    'people_tag' => 'Date',
    'people_display_text' => 'Unforgettable for: Proposal Experiences',
    'estimated_duration_minutes' => 300,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Comfortable clothing',
    'website_url' => 'https://luxuryexperiences.ca/',
    'booking_url' => 'https://luxuryexperiences.ca/helicopter-picnic/',
],

// Low-$$-Large Group
[
    'activity_title' => 'Group Meditation & Mindfulness Workshop',
    'activity_type' => 'Wellness',
    'venue_name' => 'Mindfulness Studio Toronto',
    'description' => 'Large group meditation session with guided mindfulness practices and tea ceremony.',
    'address' => '123 Queen St W, Toronto, ON M5H 2M9',
    'latitude' => 43.6505,
    'longitude' => -79.3840,
    'budget_tag' => '$$',
    'budget_display_text' => '$25-40',
    'energy_tag' => 'Low',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Peaceful for: Corporate Wellness',
    'estimated_duration_minutes' => 120,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Comfortable clothing',
    'website_url' => 'https://mindfulnesstoronto.ca/',
    'booking_url' => 'https://mindfulnesstoronto.ca/group-sessions/',
],

// Low-$$$-Small Group
[
    'activity_title' => 'Private Wine Cellar Tour & Tasting',
    'activity_type' => 'Wine Tasting',
    'venue_name' => 'Sommellerie Wine Cellar',
    'description' => 'Exclusive small group wine cellar tour with sommelier-led tasting of rare vintages.',
    'address' => '456 King St W, Toronto, ON M5V 1L7',
    'latitude' => 43.6441,
    'longitude' => -79.3951,
    'budget_tag' => '$$$',
    'budget_display_text' => '$80-120',
    'energy_tag' => 'Low',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Sophisticated for: Wine Enthusiasts',
    'estimated_duration_minutes' => 150,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'None',
    'website_url' => 'https://sommellerie.ca/',
    'booking_url' => 'https://sommellerie.ca/private-tastings/',
],

// Low-$$$-Large Group
[
    'activity_title' => 'Group Pottery Workshop',
    'activity_type' => 'Art',
    'venue_name' => 'Harbourfront Centre Craft Studio',
    'description' => 'Large group pottery workshop with professional instruction and glazing session.',
    'address' => '235 Queens Quay W, Toronto, ON M5J 2G8',
    'latitude' => 43.6386,
    'longitude' => -79.3816,
    'budget_tag' => '$$$',
    'budget_display_text' => '$60-90',
    'energy_tag' => 'Low',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Creative for: Team Building',
    'estimated_duration_minutes' => 180,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Apron provided',
    'website_url' => 'https://harbourfrontcentre.com/',
    'booking_url' => 'https://harbourfrontcentre.com/pottery-workshops/',
],

// MEDIUM ENERGY MISSING COMBINATIONS

// Medium-$-Solo
[
    'activity_title' => 'Solo Rock Climbing at Basecamp',
    'activity_type' => 'Sports',
    'venue_name' => 'Basecamp Climbing',
    'description' => 'Indoor rock climbing with instruction and equipment rental, perfect for solo fitness challenge.',
    'address' => '677 Bloor St W, Toronto, ON M6G 1L3',
    'latitude' => 43.6634,
    'longitude' => -79.4108,
    'budget_tag' => '$',
    'budget_display_text' => '$20-30',
    'energy_tag' => 'Medium',
    'people_tag' => 'Solo',
    'people_display_text' => 'Challenging for: Solo Fitness',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Athletic wear',
    'website_url' => 'https://basecampclimbing.ca/',
    'booking_url' => 'https://basecampclimbing.ca/day-passes/',
],

// Medium-$-Date
[
    'activity_title' => 'Outdoor Skating at Nathan Phillips Square',
    'activity_type' => 'Sports',
    'venue_name' => 'Nathan Phillips Square',
    'description' => 'Romantic outdoor ice skating with skate rental and hot chocolate from nearby vendors.',
    'address' => '100 Queen St W, Toronto, ON M5H 2N2',
    'latitude' => 43.6534,
    'longitude' => -79.3839,
    'budget_tag' => '$',
    'budget_display_text' => '$10-20',
    'energy_tag' => 'Medium',
    'people_tag' => 'Date',
    'people_display_text' => 'Romantic for: Winter Dates',
    'estimated_duration_minutes' => 120,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Warm clothing',
    'website_url' => 'https://toronto.ca/explore-enjoy/recreation/skating-skiing/',
],

// Medium-$-Small Group
[
    'activity_title' => 'Escape Room Challenge',
    'activity_type' => 'Games',
    'venue_name' => 'Escape Games Canada',
    'description' => 'Team-based escape room puzzles with multiple themed rooms to choose from.',
    'address' => '42 Spadina Ave, Toronto, ON M5V 2H2',
    'latitude' => 43.6475,
    'longitude' => -79.3986,
    'budget_tag' => '$',
    'budget_display_text' => '$25-35',
    'energy_tag' => 'Medium',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Challenging for: Puzzle Teams',
    'estimated_duration_minutes' => 60,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'None',
    'website_url' => 'https://escapegames.ca/',
    'booking_url' => 'https://escapegames.ca/book-now/',
],

// Medium-$-Large Group
[
    'activity_title' => 'Beach Volleyball Tournament',
    'activity_type' => 'Sports',
    'venue_name' => 'Woodbine Beach',
    'description' => 'Organized beach volleyball tournament with equipment and referee for large groups.',
    'address' => '1675 Lake Shore Blvd E, Toronto, ON M4L 3W6',
    'latitude' => 43.6629,
    'longitude' => -79.3078,
    'budget_tag' => '$',
    'budget_display_text' => '$15-25',
    'energy_tag' => 'Medium',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Active for: Sports Groups',
    'estimated_duration_minutes' => 150,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Athletic wear, sunscreen',
    'website_url' => 'https://toronto.ca/data/parks/prd/facilities/complex/2297/index.html',
],

// Medium-$$-Date
[
    'activity_title' => 'Couples Cooking Class',
    'activity_type' => 'Cooking',
    'venue_name' => 'Dish Cooking Studio',
    'description' => 'Hands-on cooking class designed for couples with wine pairing and romantic atmosphere.',
    'address' => '390 College St, Toronto, ON M5T 1S6',
    'latitude' => 43.6552,
    'longitude' => -79.4000,
    'budget_tag' => '$$',
    'budget_display_text' => '$120-160',
    'energy_tag' => 'Medium',
    'people_tag' => 'Date',
    'people_display_text' => 'Interactive for: Culinary Couples',
    'estimated_duration_minutes' => 180,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Apron provided',
    'website_url' => 'https://dishcookingstudio.com/',
    'booking_url' => 'https://dishcookingstudio.com/couples-classes/',
],

// Medium-$$$$-Small Group
[
    'activity_title' => 'Private Golf Lesson with Pro',
    'activity_type' => 'Sports',
    'venue_name' => 'Glen Abbey Golf Club',
    'description' => 'Professional golf instruction with equipment and course access for small groups.',
    'address' => '1333 Dorval Dr, Oakville, ON L6M 4X7',
    'latitude' => 43.4615,
    'longitude' => -79.7133,
    'budget_tag' => '$$$$',
    'budget_display_text' => '$200-300',
    'energy_tag' => 'Medium',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Exclusive for: Golf Enthusiasts',
    'estimated_duration_minutes' => 240,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Golf attire',
    'website_url' => 'https://glenabbey.clublink.ca/',
    'booking_url' => 'https://glenabbey.clublink.ca/golf-lessons/',
],

// Medium-$$$$$-Date
[
    'activity_title' => 'Private Helicopter Wine Tour',
    'activity_type' => 'Adventure',
    'venue_name' => 'Niagara Wine Region',
    'description' => 'Helicopter tour of Niagara wine region with private tastings and gourmet lunch for couples.',
    'address' => 'Billy Bishop Airport, Toronto, ON',
    'latitude' => 43.6275,
    'longitude' => -79.3963,
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$1500-2500',
    'energy_tag' => 'Medium',
    'people_tag' => 'Date',
    'people_display_text' => 'Spectacular for: Anniversary Celebrations',
    'estimated_duration_minutes' => 360,
    'indoor_outdoor_status' => 'Both',
    'required_materials' => 'Comfortable clothing',
    'website_url' => 'https://niagarahelitours.com/',
    'booking_url' => 'https://niagarahelitours.com/private-tours/',
],

// Medium-$$$$$-Small Group
[
    'activity_title' => 'Private Formula 1 Simulator Experience',
    'activity_type' => 'Sports',
    'venue_name' => 'Toronto Motorsports Centre',
    'description' => 'Professional F1 simulator with coaching and competition for small groups of racing enthusiasts.',
    'address' => 'Downtown Toronto (Private Location)',
    'latitude' => 43.6532,
    'longitude' => -79.3832,
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$800-1200',
    'energy_tag' => 'Medium',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Thrilling for: Racing Enthusiasts',
    'estimated_duration_minutes' => 180,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Comfortable clothing',
    'website_url' => 'https://torontomotorsports.com/',
    'booking_url' => 'https://torontomotorsports.com/f1-simulator/',
],

// Medium-$$$$-Solo
[
    'activity_title' => 'Private Photography Workshop',
    'activity_type' => 'Photography',
    'venue_name' => 'Toronto Photography Studio',
    'description' => 'One-on-one photography workshop with professional photographer and equipment access.',
    'address' => '789 Queen St W, Toronto, ON M6J 1G1',
    'latitude' => 43.6467,
    'longitude' => -79.4124,
    'budget_tag' => '$$$$',
    'budget_display_text' => '$200-350',
    'energy_tag' => 'Medium',
    'people_tag' => 'Solo',
    'people_display_text' => 'Creative for: Photography Enthusiasts',
    'estimated_duration_minutes' => 240,
    'indoor_outdoor_status' => 'Both',
    'required_materials' => 'Camera (can be provided)',
    'website_url' => 'https://torontophotostudio.com/',
    'booking_url' => 'https://torontophotostudio.com/private-lessons/',
],

// HIGH ENERGY MISSING COMBINATIONS

// High-$-Solo
[
    'activity_title' => 'Solo Fitness Bootcamp',
    'activity_type' => 'Fitness',
    'venue_name' => 'Trinity Bellwoods Park',
    'description' => 'High-intensity solo workout session with personal trainer in outdoor park setting.',
    'address' => '790 Queen St W, Toronto, ON M6J 1G1',
    'latitude' => 43.6467,
    'longitude' => -79.4124,
    'budget_tag' => '$',
    'budget_display_text' => '$25-40',
    'energy_tag' => 'High',
    'people_tag' => 'Solo',
    'people_display_text' => 'Intense for: Solo Fitness Enthusiasts',
    'estimated_duration_minutes' => 60,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Athletic wear, water bottle',
    'website_url' => 'https://torontobootcamp.com/',
    'booking_url' => 'https://torontobootcamp.com/solo-sessions/',
],

// High-$-Date
[
    'activity_title' => 'Competitive Mini Golf Date',
    'activity_type' => 'Games',
    'venue_name' => 'Putting Edge',
    'description' => 'Glow-in-the-dark mini golf with competitive scoring and fun challenges for couples.',
    'address' => '7601 Jane St, Vaughan, ON L4K 1X3',
    'latitude' => 43.8361,
    'longitude' => -79.5361,
    'budget_tag' => '$',
    'budget_display_text' => '$20-30',
    'energy_tag' => 'High',
    'people_tag' => 'Date',
    'people_display_text' => 'Playful for: Competitive Couples',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'None',
    'website_url' => 'https://puttingedge.com/',
    'booking_url' => 'https://puttingedge.com/locations/vaughan/',
],

// High-$-Small Group
[
    'activity_title' => 'Laser Tag Battle',
    'activity_type' => 'Games',
    'venue_name' => 'Laser Quest',
    'description' => 'Multi-level laser tag arena with team competitions and scoring systems.',
    'address' => '1000 Finch Ave W, North York, ON M3J 2V5',
    'latitude' => 43.7749,
    'longitude' => -79.4795,
    'budget_tag' => '$',
    'budget_display_text' => '$25-35',
    'energy_tag' => 'High',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Action-packed for: Competitive Friends',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Comfortable athletic wear',
    'website_url' => 'https://laserquest.com/',
    'booking_url' => 'https://laserquest.com/book-now/',
],

// High-$$$-Solo
[
    'activity_title' => 'Solo Motorcycle Track Day',
    'activity_type' => 'Sports',
    'venue_name' => 'Canadian Tire Motorsport Park',
    'description' => 'Professional motorcycle track experience with bike rental and safety instruction.',
    'address' => '3233 Concession Rd 2, Bowmanville, ON L1C 3K6',
    'latitude' => 44.0797,
    'longitude' => -78.6869,
    'budget_tag' => '$$$',
    'budget_display_text' => '$300-500',
    'energy_tag' => 'High',
    'people_tag' => 'Solo',
    'people_display_text' => 'Adrenaline for: Solo Thrill Seekers',
    'estimated_duration_minutes' => 480,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Motorcycle license, gear provided',
    'website_url' => 'https://canadiantiremotorsportpark.com/',
    'booking_url' => 'https://canadiantiremotorsportpark.com/track-days/',
],

// High-$$$$$-Small Group
[
    'activity_title' => 'Private Supercar Track Experience',
    'activity_type' => 'Adventure',
    'venue_name' => 'Shannonville Motorsport Park',
    'description' => 'Drive supercars (Ferrari, Lamborghini) on professional track with instruction and photography.',
    'address' => '7047 Old Hwy 2, Shannonville, ON K0K 3A0',
    'latitude' => 44.2422,
    'longitude' => -77.1456,
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$2000-4000',
    'energy_tag' => 'High',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Ultimate for: Supercar Enthusiasts',
    'estimated_duration_minutes' => 360,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Valid driver\'s license',
    'website_url' => 'https://supercartrack.ca/',
    'booking_url' => 'https://supercartrack.ca/private-experiences/',
],

// SPECIAL BUDGET COMBINATIONS

// High-$$$$-Solo
[
    'activity_title' => 'Private Skydiving Experience',
    'activity_type' => 'Adventure',
    'venue_name' => 'Skydive Toronto',
    'description' => 'Solo tandem skydiving with professional instructor and video package.',
    'address' => 'Baldwin Airport, Baldwin, ON',
    'latitude' => 43.8667,
    'longitude' => -79.5167,
    'budget_tag' => '$$$$',
    'budget_display_text' => '$400-600',
    'energy_tag' => 'High',
    'people_tag' => 'Solo',
    'people_display_text' => 'Extreme for: Adrenaline Junkies',
    'estimated_duration_minutes' => 240,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Comfortable clothing, closed shoes',
    'website_url' => 'https://skydivetoronto.com/',
    'booking_url' => 'https://skydivetoronto.com/book-jump/',
],

// Low-$-Solo
[
    'activity_title' => 'Solo Meditation at Allan Gardens',
    'activity_type' => 'Wellness',
    'venue_name' => 'Allan Gardens Conservatory',
    'description' => 'Peaceful solo meditation session in tropical conservatory setting.',
    'address' => '160 Gerrard St E, Toronto, ON M5A 2E5',
    'latitude' => 43.6626,
    'longitude' => -79.3647,
    'budget_tag' => '$',
    'budget_display_text' => 'Free',
    'energy_tag' => 'Low',
    'people_tag' => 'Solo',
    'people_display_text' => 'Peaceful for: Solo Reflection',
    'estimated_duration_minutes' => 60,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Comfortable clothing',
    'website_url' => 'https://toronto.ca/data/parks/prd/facilities/complex/1/index.html',
],

// Low-$-Date
[
    'activity_title' => 'Romantic Sunset Walk at Harbourfront',
    'activity_type' => 'Walking',
    'venue_name' => 'Harbourfront Centre',
    'description' => 'Leisurely romantic walk along the waterfront with sunset viewing.',
    'address' => '235 Queens Quay W, Toronto, ON M5J 2G8',
    'latitude' => 43.6386,
    'longitude' => -79.3816,
    'budget_tag' => '$',
    'budget_display_text' => 'Free',
    'energy_tag' => 'Low',
    'people_tag' => 'Date',
    'people_display_text' => 'Romantic for: Budget-Friendly Dates',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Comfortable walking shoes',
    'website_url' => 'https://harbourfrontcentre.com/',
],

// Low-$-Small Group
[
    'activity_title' => 'Group Book Club at Library',
    'activity_type' => 'Culture',
    'venue_name' => 'Toronto Public Library',
    'description' => 'Organized book discussion group in comfortable library setting.',
    'address' => '789 Yonge St, Toronto, ON M4W 2G8',
    'latitude' => 43.6706,
    'longitude' => -79.3879,
    'budget_tag' => '$',
    'budget_display_text' => 'Free',
    'energy_tag' => 'Low',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Intellectual for: Book Lovers',
    'estimated_duration_minutes' => 120,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Selected book',
    'website_url' => 'https://www.torontopubliclibrary.ca/',
],

// Low-$-Large Group
[
    'activity_title' => 'Group Tai Chi in the Park',
    'activity_type' => 'Wellness',
    'venue_name' => 'Trinity Bellwoods Park',
    'description' => 'Large group Tai Chi session led by certified instructor in peaceful park setting.',
    'address' => '790 Queen St W, Toronto, ON M6J 1G1',
    'latitude' => 43.6467,
    'longitude' => -79.4124,
    'budget_tag' => '$',
    'budget_display_text' => '$10-15',
    'energy_tag' => 'Low',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Harmonious for: Wellness Groups',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => 'Comfortable clothing',
    'website_url' => 'https://torontotaichi.com/',
],
[
    'activity_title' => 'Duel Citizens',
    'activity_type' => 'Comedy',
    'venue_name' => 'Second City Toronto',
    'description' => 'The Second City is renown as the worlds premier comedy theatre, with critically-acclaimed live improv and sketch comedy shows on stage every night.',
    'address' => 'The Second City, 110 Harbour St, Toronto, ON M5J 0B6',
    'latitude' => 43.6532,
    'longitude' => -79.3832,
    'budget_tag' => '$$$',
    'budget_display_text' => '$35-55',
    'energy_tag' => 'High',
    'people_tag' => 'Solo',
    'people_display_text' => 'Perfect for: Solo',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Ticket',
    'website_url' => 'https://www.secondcity.com/toronto',
    'booking_url' => 'https://www.secondcity.com/shows/toronto/duel-citizens-tor',
],
[
    'activity_title' => 'Rhune Mountain',
    'activity_type' => 'Fantasy Party',
    'venue_name' => 'Bovine Sex Club',
    'description' => 'In operation since January 1991, the Bovine Sex Club  has at various times found itself at the forefront of Torontos rock, punk, heavy metal, alternative, and rockabilly music scenes..',
    'address' => '542 Queen St W, Toronto, ON M5V 2B5',
    'latitude' => 43.6483,
    'longitude' => -79.4057,
    'budget_tag' => '$$',
    'budget_display_text' => '$15-35',
    'energy_tag' => 'High',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Perfect for: Small Group',
    'estimated_duration_minutes' => 60,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Ticket',
    'website_url' => 'https://www.bovinesexclub.com/#HOME',
],
[
    'activity_title' => 'Karaoke',
    'activity_type' => 'Music',
    'venue_name' => 'Bar+ Karaoke Lounge',
    'description' => 'Located in the heart of downtown Toronto at 360 Yonge Street, we bring you a one-of-a-kind experience where music, fun, and unforgettable memories take centre stage.',
    'address' => '360 Yonge St, Toronto, ON M5B 1S5',
    'latitude' => 43.6568,
    'longitude' => -79.3807,
    'budget_tag' => '$$$',
    'budget_display_text' => '$40-75',
    'energy_tag' => 'High',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Perfect for: Small Group',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'ID for age verification',
    'website_url' => 'https://bar-plus.com/',
    'booking_url' => 'https://bar-plus.com/reservations',
],
[
    'activity_title' => 'Just dance night',
    'activity_type' => 'Dance',
    'venue_name' => 'Black Eagle',
    'description' => 'Adult venue with dark, industrial decor catering to the gay leather & denim communities.',
    'address' => '457 Church St, Toronto, ON M4Y 2C5',
    'latitude' => 43.6615,
    'longitude' => -79.3804,
    'budget_tag' => '$$',
    'budget_display_text' => '$20-35',
    'energy_tag' => 'High',
    'people_tag' => 'Solo',
    'people_display_text' => 'Perfect for: Solo',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'None',
    'website_url' => 'https://www.blackeagletoronto.com/',
],
[
    'activity_title' => 'Isabella Sofia Quartet, Jazz Standards',
    'activity_type' => 'Music',
    'venue_name' => 'The Emmet Ray Whisky Jazz Bar',
    'description' => 'Hangout with a long whisky list hosting a wide range of live bands, plus pub food.',
    'address' => '924 College St, Toronto, ON M6H 1A4',
    'latitude' => 43.6558,
    'longitude' => -79.4181,
    'budget_tag' => '$',
    'budget_display_text' => '$5-15',
    'energy_tag' => 'Low',
    'people_tag' => 'Solo',
    'people_display_text' => 'Perfect for: Solo',
    'estimated_duration_minutes' => 90,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'Music enthusiasm',
    'website_url' => 'https://www.theemmetray.com/',
],
[
    'activity_title' => 'Pool Relaxation',
    'activity_type' => 'Bar',
    'venue_name' => 'Cabana Poolbar',
    'description' => 'Luxury outdoor bar & lounge centered on a large pool with private cabanas, DJs & upscale eats.',
    'address' => '11 Polson St, Toronto, ON M5A 1A4',
    'latitude' => 43.6409,
    'longitude' => -79.3548,
    'budget_tag' => '$$$$',
    'budget_display_text' => '$40-80',
    'energy_tag' => 'Low',
    'people_tag' => 'Date',
    'people_display_text' => 'Perfect for: Date',
    'estimated_duration_minutes' => 60,
    'indoor_outdoor_status' => 'Outdoor',
    'required_materials' => '$20 Pool Access',
    'website_url' => 'https://cabanatoronto.com/',
],
[
    'activity_title' => 'Coffee talk',
    'activity_type' => 'Coffee Bar',
    'venue_name' => 'Boxcar Social',
    'description' => 'Snug, rustic-chic coffeehouse with a patio serving espresso, craft brews & charcuterie plates..',
    'address' => '1208 Yonge St, Toronto, ON M4T 1W1',
    'latitude' => 43.6825,
    'longitude' => -79.3968,
    'budget_tag' => '$',
    'budget_display_text' => '$5-15',
    'energy_tag' => 'Low',
    'people_tag' => 'Date',
    'people_display_text' => 'Perfect for: Date',
    'estimated_duration_minutes' => 60,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'None',
    'website_url' => 'https://boxcarsocial.ca/pages/summerhill',
],
[
    'activity_title' => 'Luxury Bar Date',
    'activity_type' => 'Bar',
    'venue_name' => 'BarChef',
    'description' => 'Dimly lit, intimate hangout offering creative cocktails, with over 5,000 housemade bitters.',
    'address' => '472 Queen St W, Toronto, ON M5V 2B2',
    'latitude' => 43.6471,
    'longitude' => -79.3978,
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$100-150',
    'energy_tag' => 'Medium',
    'people_tag' => 'Date',
    'people_display_text' => 'Perfect for: Date',
    'estimated_duration_minutes' => 60,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'None',
    'website_url' => 'https://boxcarsocial.ca/pages/summerhill',
],
[
    'activity_title' => 'Luxury Bar Talk',
    'activity_type' => 'Bar',
    'venue_name' => 'LIBRARY BAR',
    'description' => 'Refined bar in the Royal York Hotel for martinis, cocktails & wine, plus thoughtfully sourced meals.',
    'address' => '100 Front St W, Toronto, ON M5J 1E3',
    'latitude' => 43.6460,
    'longitude' => -79.3829,
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$100-150',
    'energy_tag' => 'Medium',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Perfect for: Small Group',
    'estimated_duration_minutes' => 60,
    'indoor_outdoor_status' => 'Indoor',
    'required_materials' => 'None',
    'website_url' => 'https://www.librarybartoronto.com/',
]

        ];

        foreach ($activities as $activityData) {
            if (isset($activityData['activity_title'], $activityData['activity_type'])) {
                Activity::create($activityData);
            }
        }
    }
}