<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Restaurant;

class RestaurantSeeder extends Seeder
{
    public function run()
    {
        $restaurants = [
            [
                'name' => 'Tim Hortons',
                'address' => '1 Blue Jays Way, Toronto, ON M5V 1J1',
                'latitude' => 43.6414,
                'longitude' => -79.3894,
                'cuisine_type' => 'Coffee & Donuts',
                'description_snippet' => 'Canadian coffee chain with quick bites',
                'budget_tag' => '$',
                'budget_display_text' => '$5-12',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Good for: Quick Coffee',
                'ambiance_tags' => 'Casual,Quick,Canadian',
                'website_url' => 'https://timhortons.com',
                'phone_number' => '(416) 341-3663',
            ],
            [
                'name' => 'Café Diplomatico',
                'address' => '594 College St, Toronto, ON M6G 1B3',
                'latitude' => 43.6567,
                'longitude' => -79.4029,
                'cuisine_type' => 'Italian Café',
                'description_snippet' => 'Cozy Italian café perfect for quiet conversations',
                'budget_tag' => '$$',
                'budget_display_text' => '$15-30',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Perfect for: Intimate Dates',
                'ambiance_tags' => 'Cozy,Romantic,Quiet',
                'website_url' => 'https://cafediplomatico.ca',
                'phone_number' => '(416) 534-4637',
            ],
            [
                'name' => 'Sunset Grill',
                'address' => '2006 Yonge St, Toronto, ON M4S 1Z9',
                'latitude' => 43.7089,
                'longitude' => -79.3957,
                'cuisine_type' => 'Canadian Comfort',
                'description_snippet' => 'Relaxed family restaurant with comfort food',
                'budget_tag' => '$$',
                'budget_display_text' => '$18-35',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Great for: Family & Friends',
                'ambiance_tags' => 'Casual,Family-Friendly,Relaxed',
                'website_url' => 'https://sunsetgrill.ca',
                'phone_number' => '(416) 489-7291',
            ],
            [
                'name' => 'St. Lawrence Market',
                'address' => '93 Front St E, Toronto, ON M5E 1C3',
                'latitude' => 43.6487,
                'longitude' => -79.3716,
                'cuisine_type' => 'Food Market',
                'description_snippet' => 'Historic market with diverse food vendors',
                'budget_tag' => '$',
                'budget_display_text' => '$10-30',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Fun for: Groups & Families',
                'ambiance_tags' => 'Lively,Casual,Historic',
                'website_url' => 'https://www.stlawrencemarket.com',
                'phone_number' => '(416) 392-7219',
            ],

            // MEDIUM ENERGY RESTAURANTS
            [
                'name' => 'Osmow\'s Shawarma',
                'address' => '277 Victoria St, Toronto, ON M5B 1W2',
                'latitude' => 43.6569,
                'longitude' => -79.3805,
                'cuisine_type' => 'Middle Eastern',
                'description_snippet' => 'Fresh Mediterranean and Middle Eastern cuisine',
                'budget_tag' => '$',
                'budget_display_text' => '$10-20',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Good for: Quick Solo Meals',
                'ambiance_tags' => 'Casual,Quick Service,Healthy',
                'website_url' => 'https://osmows.com',
                'phone_number' => '(416) 368-4299',
            ],
            [
                'name' => 'Richmond Station',
                'address' => '1 Richmond St W, Toronto, ON M5H 3W4',
                'latitude' => 43.6505,
                'longitude' => -79.3789,
                'cuisine_type' => 'Contemporary Canadian',
                'description_snippet' => 'Farm-to-table Canadian cuisine',
                'budget_tag' => '$$$',
                'budget_display_text' => '$45-70',
                'energy_tag' => 'Medium',
                'people_tag' => 'Date',
                'people_display_text' => 'Perfect for: Date Night',
                'ambiance_tags' => 'Modern,Local,Sophisticated',
                'website_url' => 'https://richmondstation.ca',
                'phone_number' => '(647) 748-1444',
            ],
            [
                'name' => 'Pai Northern Thai',
                'address' => '18 Duncan St, Toronto, ON M5H 3G8',
                'latitude' => 43.6464,
                'longitude' => -79.3897,
                'cuisine_type' => 'Thai',
                'description_snippet' => 'Authentic Northern Thai street food',
                'budget_tag' => '$$',
                'budget_display_text' => '$25-40',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Great for: Friends',
                'ambiance_tags' => 'Vibrant,Authentic,Spicy',
                'website_url' => 'https://paitoronto.com',
                'phone_number' => '(647) 348-7205',
            ],
            [
                'name' => 'The Burger\'s Priest',
                'address' => '212 Adelaide St E, Toronto, ON M5A 1N1',
                'latitude' => 43.6506,
                'longitude' => -79.3693,
                'cuisine_type' => 'Burgers',
                'description_snippet' => 'Gourmet burger joint with cult following',
                'budget_tag' => '$$',
                'budget_display_text' => '$15-25',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Good for: Group Hangouts',
                'ambiance_tags' => 'Casual,Gourmet Burgers,Hip',
                'website_url' => 'https://theburgerspriest.com',
                'phone_number' => '(647) 347-7991',
            ],

            // HIGH ENERGY RESTAURANTS
            [
                'name' => 'Kinka Izakaya',
                'address' => '559 Bloor St W, Toronto, ON M5S 1Y6',
                'latitude' => 43.6634,
                'longitude' => -79.4108,
                'cuisine_type' => 'Japanese Izakaya',
                'description_snippet' => 'Lively Japanese pub with energetic atmosphere',
                'budget_tag' => '$$',
                'budget_display_text' => '$30-50',
                'energy_tag' => 'High',
                'people_tag' => 'Solo',
                'people_display_text' => 'Great for: Solo Dining at Bar',
                'ambiance_tags' => 'Lively,Authentic,Energetic',
                'website_url' => 'https://kinkaizakaya.com',
                'phone_number' => '(647) 748-8862',
            ],
            [
                'name' => 'The Keg Mansion',
                'address' => '515 Jarvis St, Toronto, ON M4Y 2H9',
                'latitude' => 43.6658,
                'longitude' => -79.3733,
                'cuisine_type' => 'Steakhouse',
                'description_snippet' => 'Upscale steakhouse in a historic mansion',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$60-100',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Perfect for: Special Date Night',
                'ambiance_tags' => 'Upscale,Romantic,Historic',
                'website_url' => 'https://kegmansion.com',
                'phone_number' => '(416) 964-6609',
            ],
            [
                'name' => 'Momofuku Noodle Bar',
                'address' => '190 University Ave, Toronto, ON M5H 0A3',
                'latitude' => 43.6491,
                'longitude' => -79.3863,
                'cuisine_type' => 'Asian Fusion',
                'description_snippet' => 'Modern Asian cuisine and craft cocktails',
                'budget_tag' => '$$$',
                'budget_display_text' => '$35-55',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Great for: Night Out',
                'ambiance_tags' => 'Modern,Asian Fusion,Trendy',
                'website_url' => 'https://momofuku.com/toronto',
                'phone_number' => '(647) 253-8000',
            ],
            [
                'name' => 'Jacobs & Co. Steakhouse',
                'address' => '12 Brant St, Toronto, ON M5V 2M1',
                'latitude' => 43.6426,
                'longitude' => -79.4012,
                'cuisine_type' => 'Steakhouse',
                'description_snippet' => 'Premium steakhouse experience',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$100-150',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Ideal for: Celebrations',
                'ambiance_tags' => 'Luxury,Premium,Sophisticated',
                'website_url' => 'https://jacobssteakhouse.com',
                'phone_number' => '(416) 366-0200',
            ],

            // ADDITIONAL BUDGET COVERAGE
            [
                'name' => 'Smoke\'s Poutinerie',
                'address' => '99 Church St, Toronto, ON M5C 2G3',
                'latitude' => 43.6507,
                'longitude' => -79.3747,
                'cuisine_type' => 'Canadian',
                'description_snippet' => 'Gourmet poutine and comfort food',
                'budget_tag' => '$',
                'budget_display_text' => '$8-15',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Good for: Casual Groups',
                'ambiance_tags' => 'Casual,Comfort Food,Quick',
                'website_url' => 'https://smokespoutinerie.com',
                'phone_number' => '(416) 368-4299',
            ],
            [
                'name' => 'Canoe Restaurant',
                'address' => '66 Wellington St W, Toronto, ON M5K 1H6',
                'latitude' => 43.6481,
                'longitude' => -79.3808,
                'cuisine_type' => 'Contemporary Canadian',
                'description_snippet' => 'Fine dining with panoramic city views',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$80-120',
                'energy_tag' => 'Medium',
                'people_tag' => 'Date',
                'people_display_text' => 'Perfect for: Special Occasions',
                'ambiance_tags' => 'Fine Dining,City Views,Romantic',
                'website_url' => 'https://oliverbonacini.com/canoe',
                'phone_number' => '(416) 364-0054',
            ],
            [
                'name' => 'Scaramouche Restaurant',
                'address' => '1 Benvenuto Pl, Toronto, ON M4V 2L1',
                'latitude' => 43.6850,
                'longitude' => -79.4094,
                'cuisine_type' => 'French',
                'description_snippet' => 'Upscale French dining with city skyline views',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$120-180',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Perfect for: Anniversary',
                'ambiance_tags' => 'Luxury,French,Scenic Views',
                'website_url' => 'https://scaramoucherestaurant.com',
                'phone_number' => '(416) 961-8011',
            ],

            // FILLING ALL COMBINATIONS - RESTAURANTS
            // LOW ENERGY
            [
                'name' => 'Fresh Restaurants',
                'address' => '894 Queen St W, Toronto, ON M6J 1G3',
                'latitude' => 43.6473,
                'longitude' => -79.4124,
                'cuisine_type' => 'Vegan/Vegetarian',
                'description_snippet' => 'Healthy and fresh plant-based cuisine in a relaxed setting.',
                'budget_tag' => '$$',
                'budget_display_text' => '$20-35',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Good for: Healthy Solo Meal',
                'ambiance_tags' => 'Casual,Healthy,Relaxed',
                'website_url' => 'https://freshplantpowered.com/',
                'phone_number' => '(416) 594-3747',
            ],
            [
                'name' => 'Pizzeria Libretto',
                'address' => '221 Ossington Ave, Toronto, ON M6J 2Z8',
                'latitude' => 43.6477,
                'longitude' => -79.4184,
                'cuisine_type' => 'Neapolitan Pizza',
                'description_snippet' => 'Authentic Neapolitan pizza in a cozy, vibrant atmosphere.',
                'budget_tag' => '$$',
                'budget_display_text' => '$25-45',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Perfect for: Casual Group Dinners',
                'ambiance_tags' => 'Cozy,Vibrant,Italian',
                'website_url' => 'https://pizzerialibretto.com/',
                'phone_number' => '(416) 532-6800',
            ],
            [
                'name' => 'Kensington Market Eateries',
                'address' => 'Various, Kensington Market, Toronto',
                'latitude' => 43.6548,
                'longitude' => -79.3999,
                'cuisine_type' => 'Eclectic/Street Food',
                'description_snippet' => 'Diverse range of casual and affordable street food and small eateries.',
                'budget_tag' => '$',
                'budget_display_text' => '$10-25',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Explore for: Adventurous Foodies',
                'ambiance_tags' => 'Eclectic,Casual,Bohemian',
                'website_url' => 'https://kensington-market.ca/',
                'phone_number' => null,
            ],
            [
                'name' => 'The Senator',
                'address' => '249 Victoria St, Toronto, ON M5B 1T8',
                'latitude' => 43.6559,
                'longitude' => -79.3798,
                'cuisine_type' => 'Diner/Classic American',
                'description_snippet' => 'Historic diner serving classic comfort food since 1929.',
                'budget_tag' => '$$',
                'budget_display_text' => '$20-40',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Timeless for: Nostalgic Groups',
                'ambiance_tags' => 'Retro,Classic,Comfort Food',
                'website_url' => 'https://thesenator.com/',
                'phone_number' => '(416) 364-7517',
            ],
            [
                'name' => 'Rasa',
                'address' => '196 Robert St, Toronto, ON M5S 2K7',
                'latitude' => 43.6666,
                'longitude' => -79.4034,
                'cuisine_type' => 'Modern Canadian',
                'description_snippet' => 'Upscale casual dining with creative Canadian dishes.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$60-90',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Modern for: Sophisticated Couples',
                'ambiance_tags' => 'Modern,Chic,Upscale Casual',
                'website_url' => 'https://rasatoronto.com/',
                'phone_number' => '(647) 345-8121',
            ],
            [
                'name' => 'Aloette',
                'address' => '163 Spadina Ave, Toronto, ON M5V 2L6',
                'latitude' => 43.6475,
                'longitude' => -79.3986,
                'cuisine_type' => 'French Diner',
                'description_snippet' => 'Casual French diner from the Alo team, offering elevated comfort food.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$50-80',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Chic for: Solo Indulgence',
                'ambiance_tags' => 'Chic,Diner,French',
                'website_url' => 'https://aloetterestaurant.com/',
                'phone_number' => '(416) 260-5555',
            ],
            [
                'name' => 'Bar Isabel',
                'address' => '797 College St, Toronto, ON M6G 1C7',
                'latitude' => 43.6565,
                'longitude' => -79.4140,
                'cuisine_type' => 'Spanish Tapas',
                'description_snippet' => 'Lively Spanish tapas bar with an extensive wine list.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$75-125',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Vibrant for: Intimate Gatherings',
                'ambiance_tags' => 'Lively,Authentic,Spanish',
                'website_url' => 'https://barisabel.com/',
                'phone_number' => '(416) 532-2222',
            ],
            [
                'name' => 'Buca Osteria & Bar (Yorkville)',
                'address' => '53 Scollard St, Toronto, ON M5R 1G1',
                'latitude' => 43.6706,
                'longitude' => -79.3907,
                'cuisine_type' => 'Italian',
                'description_snippet' => 'Upscale Italian restaurant known for seafood and handmade pasta.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$100-150',
                'energy_tag' => 'Low',
                'people_tag' => 'Solo',
                'people_display_text' => 'Refined for: Solo Fine Dining',
                'ambiance_tags' => 'Upscale,Italian,Sophisticated',
                'website_url' => 'https://www.buca.ca/yorkville',
                'phone_number' => '(416) 962-2822',
            ],
            [
                'name' => 'Alo Restaurant',
                'address' => '163 Spadina Ave, Toronto, ON M5V 2L6',
                'latitude' => 43.6475,
                'longitude' => -79.3986,
                'cuisine_type' => 'Modern French',
                'description_snippet' => 'Michelin-starred modern French tasting menu experience.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$150-300+',
                'energy_tag' => 'Low',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Exquisite for: Gourmands',
                'ambiance_tags' => 'Michelin,Luxury,Modern',
                'website_url' => 'https://alorestaurant.com/',
                'phone_number' => '(416) 260-2222',
            ],
            [
                'name' => 'Auberge du Pommier',
                'address' => '4150 Yonge St, North York, ON M2P 2C6',
                'latitude' => 43.7423,
                'longitude' => -79.4005,
                'cuisine_type' => 'French',
                'description_snippet' => 'Elegant French dining in a charming, rustic setting.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$150-250',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Refined for: Exclusive Events',
                'ambiance_tags' => 'Elegant,French,Charming',
                'website_url' => 'https://oliverbonacini.com/aubergedupommier',
                'phone_number' => '(416) 222-2220',
            ],
            [
                'name' => 'Seven Lives Tacos y Mariscos',
                'address' => '69 Kensington Ave, Toronto, ON M5T 2K2',
                'latitude' => 43.6541,
                'longitude' => -79.3992,
                'cuisine_type' => 'Mexican',
                'description_snippet' => 'Popular spot for Baja-style tacos in a casual setting.',
                'budget_tag' => '$',
                'budget_display_text' => '$10-20',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Lively for: Casual Group Bites',
                'ambiance_tags' => 'Casual,Lively,Mexican',
                'website_url' => 'https://sevenlivestacos.ca/',
                'phone_number' => '(416) 367-7773',
            ],

            // MEDIUM ENERGY
            [
                'name' => 'Hot Docs Ted Rogers Cinema',
                'address' => '506 Bloor St W, Toronto, ON M5S 1Y5',
                'latitude' => 43.6644,
                'longitude' => -79.4069,
                'cuisine_type' => 'Cinema Snacks/Bar',
                'description_snippet' => 'Independent cinema with a licensed bar, good for a pre-show bite.',
                'budget_tag' => '$',
                'budget_display_text' => '$15-25',
                'energy_tag' => 'Medium',
                'people_tag' => 'Date',
                'people_display_text' => 'Casual for: Pre-Show Bites',
                'ambiance_tags' => 'Casual,Art House,Lively',
                'website_url' => 'https://hotdocs.ca/cinema',
                'phone_number' => '(416) 637-3123',
            ],
            [
                'name' => 'Planta Queen',
                'address' => '180 Queen St W, Toronto, ON M5V 3X3',
                'latitude' => 43.6489,
                'longitude' => -79.3879,
                'cuisine_type' => 'Plant-Based Asian',
                'description_snippet' => 'Stylish plant-based Asian cuisine with a vibrant atmosphere.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$50-80',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Trendy for: Vegan Friends',
                'ambiance_tags' => 'Trendy,Stylish,Vibrant',
                'website_url' => 'https://www.plantarestaurants.com/location/planta-queen/',
                'phone_number' => '(647) 348-7000',
            ],
            [
                'name' => 'Bar Raval',
                'address' => '505 College St, Toronto, ON M6G 1A6',
                'latitude' => 43.6558,
                'longitude' => -79.4035,
                'cuisine_type' => 'Spanish Tapas/Cocktails',
                'description_snippet' => 'Renowned Spanish tapas bar with unique cocktails and a lively standing-room only vibe.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$40-70',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Energetic for: Solo Explorers',
                'ambiance_tags' => 'Vibrant,Trendy,Spanish',
                'website_url' => 'https://thisisbarraval.com/',
                'phone_number' => '(647) 344-8800',
            ],
            [
                'name' => 'Terroni (Queen St W)',
                'address' => '720 Queen St W, Toronto, ON M6J 1E8',
                'latitude' => 43.6467,
                'longitude' => -79.4079,
                'cuisine_type' => 'Italian',
                'description_snippet' => 'Popular Italian restaurant with authentic dishes and bustling atmosphere.',
                'budget_tag' => '$$',
                'budget_display_text' => '$30-55',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Bustling for: Solo Dining',
                'ambiance_tags' => 'Bustling,Authentic,Italian',
                'website_url' => 'https://terroni.com/locations/queen/',
                'phone_number' => '(416) 504-0320',
            ],
            [
                'name' => 'Communion Restaurant',
                'address' => '200 Main St, Toronto, ON M4E 2W1',
                'latitude' => 43.6702,
                'longitude' => -79.3090,
                'cuisine_type' => 'Modern Canadian',
                'description_snippet' => 'Upscale dining with a focus on local ingredients and contemporary Canadian cuisine.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$75-120',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Elegant for: Solo Indulgence',
                'ambiance_tags' => 'Modern,Local,Refined',
                'website_url' => 'https://www.communionrestaurant.com/',
                'phone_number' => '(416) 691-8888',
            ],
            [
                'name' => 'Blue Blood Steakhouse',
                'address' => '1 Austin Terrace, Toronto, ON M5R 1X8',
                'latitude' => 43.6780,
                'longitude' => -79.4094,
                'cuisine_type' => 'Steakhouse',
                'description_snippet' => 'Luxury steakhouse located within Casa Loma with an opulent atmosphere.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$120-200',
                'energy_tag' => 'Medium',
                'people_tag' => 'Solo',
                'people_display_text' => 'Indulgent for: Solo Splurge',
                'ambiance_tags' => 'Luxury,Opulent,Steakhouse',
                'website_url' => 'https://bluebloodsteakhouse.com/',
                'phone_number' => '(416) 353-8477',
            ],
            [
                'name' => 'George Restaurant',
                'address' => '119 Queen St E, Toronto, ON M5C 1S9',
                'latitude' => 43.6534,
                'longitude' => -79.3732,
                'cuisine_type' => 'Contemporary Canadian',
                'description_snippet' => 'Elegant dining with creative tasting menus focusing on seasonal ingredients.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$150-250',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Sophisticated for: Group Celebrations',
                'ambiance_tags' => 'Elegant,Creative,Seasonal',
                'website_url' => 'https://georgeonqueen.com/',
                'phone_number' => '(416) 862-1111',
            ],
            [
                'name' => 'Kost',
                'address' => '80 Blue Jays Way, Toronto, ON M5V 2G3',
                'latitude' => 43.6444,
                'longitude' => -79.3888,
                'cuisine_type' => 'Californian/Rooftop',
                'description_snippet' => 'Rooftop restaurant with stunning city views and Californian-inspired cuisine.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$60-100',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Panoramic for: Group Dining',
                'ambiance_tags' => 'Rooftop,Trendy,Scenic Views',
                'website_url' => 'https://kosttoronto.com/',
                'phone_number' => '(416) 979-2700',
            ],
            [
                'name' => 'Oretta',
                'address' => '633 King St W, Toronto, ON M5V 1M5',
                'latitude' => 43.6450,
                'longitude' => -79.3970,
                'cuisine_type' => 'Italian',
                'description_snippet' => 'Stylish Italian restaurant with a vibrant atmosphere and classic dishes.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$50-90',
                'energy_tag' => 'Medium',
                'people_tag' => 'Date',
                'people_display_text' => 'Stylish for: Lively Dates',
                'ambiance_tags' => 'Stylish,Vibrant,Italian',
                'website_url' => 'https://oretta.to/',
                'phone_number' => '(416) 601-3911',
            ],
            [
                'name' => 'Chubby\'s Jamaican Kitchen',
                'address' => '104 Portland St, Toronto, ON M5V 2N2',
                'latitude' => 43.6433,
                'longitude' => -79.4005,
                'cuisine_type' => 'Jamaican',
                'description_snippet' => 'Lively Jamaican kitchen serving authentic jerk chicken and rum cocktails.',
                'budget_tag' => '$$',
                'budget_display_text' => '$30-50',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Energetic for: Fun Groups',
                'ambiance_tags' => 'Lively,Casual,Caribbean',
                'website_url' => 'https://chubbysjamaicankitchen.com/',
                'phone_number' => '(416) 792-8100',
            ],
            [
                'name' => 'Casa Madera',
                'address' => '550 Wellington St W, Toronto, ON M5V 2V4',
                'latitude' => 43.6416,
                'longitude' => -79.3980,
                'cuisine_type' => 'Mexican/Mediterranean',
                'description_snippet' => 'High-energy, upscale Mexican-Mediterranean dining with live entertainment.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$90-150',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Vibrant for: High-End Groups',
                'ambiance_tags' => 'Lively,Luxury,Trendy',
                'website_url' => 'https://www.casamadera.com/toronto',
                'phone_number' => '(416) 300-3333',
            ],

            // HIGH ENERGY
            [
                'name' => 'King Taps',
                'address' => '100 King St W, Toronto, ON M5X 1A6',
                'latitude' => 43.6480,
                'longitude' => -79.3800,
                'cuisine_type' => 'Pub Fare/Brewery',
                'description_snippet' => 'Massive beer hall with a lively atmosphere, sports, and classic pub food.',
                'budget_tag' => '$$',
                'budget_display_text' => '$25-45',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Lively for: Sports Fans',
                'ambiance_tags' => 'Lively,Sports Bar,Casual',
                'website_url' => 'https://kingtaps.com/',
                'phone_number' => '(647) 748-8277',
            ],
            [
                'name' => 'The Pint Public House',
                'address' => '277 Front St W, Toronto, ON M5V 2X4',
                'latitude' => 43.6433,
                'longitude' => -79.3871,
                'cuisine_type' => 'Pub Fare',
                'description_snippet' => 'Energetic pub with multiple screens for sports and a vibrant crowd.',
                'budget_tag' => '$',
                'budget_display_text' => '$20-35',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Electric for: Game Day Groups',
                'ambiance_tags' => 'Lively,Sports Bar,Casual',
                'website_url' => 'https://thepint.ca/toronto/',
                'phone_number' => '(647) 347-7468',
            ],
            [
                'name' => 'Akira Back',
                'address' => '80 Blue Jays Way, Toronto, ON M5V 2G3',
                'latitude' => 43.6444,
                'longitude' => -79.3888,
                'cuisine_type' => 'Japanese/Korean Fusion',
                'description_snippet' => 'High-end Japanese-Korean fusion with a trendy, energetic ambiance.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$90-160',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Trendy for: Upscale Groups',
                'ambiance_tags' => 'Trendy,Luxury,Energetic',
                'website_url' => 'https://akirabacktoronto.com/',
                'phone_number' => '(416) 353-8477',
            ],
            [
                'name' => 'Byblos Toronto',
                'address' => '11 Duncan St, Toronto, ON M5V 3M2',
                'latitude' => 43.6470,
                'longitude' => -79.3897,
                'cuisine_type' => 'Eastern Mediterranean',
                'description_snippet' => 'Sophisticated Eastern Mediterranean restaurant with a vibrant, upscale setting.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$70-120',
                'energy_tag' => 'High',
                'people_tag' => 'Solo',
                'people_display_text' => 'Vibrant for: Solo Diners',
                'ambiance_tags' => 'Sophisticated,Vibrant,Mediterranean',
                'website_url' => 'https://byblostoronto.com/',
                'phone_number' => '(647) 660-0081',
            ],
            [
                'name' => 'The Chase',
                'address' => '159 Wellington St W, Toronto, ON M5J 1H5',
                'latitude' => 43.6473,
                'longitude' => -79.3871,
                'cuisine_type' => 'Seafood/Contemporary',
                'description_snippet' => 'Upscale seafood restaurant with stunning rooftop views and lively atmosphere.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$100-180',
                'energy_tag' => 'High',
                'people_tag' => 'Solo',
                'people_display_text' => 'Luxurious for: Solo Celebrations',
                'ambiance_tags' => 'Rooftop,Luxury,Vibrant',
                'website_url' => 'https://thechasetoronto.com/',
                'phone_number' => '(647) 348-7000',
            ],
            [
                'name' => 'Patria',
                'address' => '478 King St W, Toronto, ON M5V 1L7',
                'latitude' => 43.6441,
                'longitude' => -79.3951,
                'cuisine_type' => 'Spanish Tapas',
                'description_snippet' => 'Lively Spanish restaurant known for its paella and vibrant atmosphere.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$50-90',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Vibrant for: Lively Dates',
                'ambiance_tags' => 'Vibrant,Spanish,Lively',
                'website_url' => 'https://patriatoronto.com/',
                'phone_number' => '(416) 901-3404',
            ],
            [
                'name' => 'Black+Blue Steakhouse',
                'address' => '1533 King St W, Toronto, ON M6K 1J6',
                'latitude' => 43.6409,
                'longitude' => -79.4310,
                'cuisine_type' => 'Steakhouse',
                'description_snippet' => 'Chic, modern steakhouse with a high-energy dining experience.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$80-140',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Sophisticated for: Group Indulgence',
                'ambiance_tags' => 'Chic,Modern,Lively',
                'website_url' => 'https://blackandbluesteakhouse.ca/toronto',
                'phone_number' => '(647) 748-8900',
            ],
            [
                'name' => 'Don Alfonso 1890',
                'address' => '1 Harbour Sq, Toronto, ON M5J 2V9',
                'latitude' => 43.6397,
                'longitude' => -79.3813,
                'cuisine_type' => 'Italian Fine Dining',
                'description_snippet' => 'Michelin-starred modern Italian cuisine with stunning lake views.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$200-400+',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Grand for: Ultimate Celebrations',
                'ambiance_tags' => 'Michelin,Luxury,Scenic Views',
                'website_url' => 'https://www.donalfonso1890.ca/',
                'phone_number' => '(416) 214-5888',
            ],
            [
                'name' => 'El Catrin Destileria',
                'address' => '18 Tank House Ln, Toronto, ON M5A 3C4',
                'latitude' => 43.6508,
                'longitude' => -79.3592,
                'cuisine_type' => 'Mexican',
                'description_snippet' => 'Vibrant and authentic Mexican cuisine in the Distillery District with a lively patio.',
                'budget_tag' => '$$',
                'budget_display_text' => '$30-55',
                'energy_tag' => 'High',
                'people_tag' => 'Date',
                'people_display_text' => 'Lively for: Dynamic Dates',
                'ambiance_tags' => 'Vibrant,Authentic,Lively',
                'website_url' => 'https://elcatrin.ca/',
                'phone_number' => '(416) 203-2121',
            ],
            [
                'name' => 'Lee Restaurant',
                'address' => '601 King St W, Toronto, ON M5V 1M5',
                'latitude' => 43.6450,
                'longitude' => -79.3965,
                'cuisine_type' => 'Asian Fusion',
                'description_snippet' => 'Celebrity chef Susur Lee\'s restaurant offering innovative Asian fusion dishes.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$60-100',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Innovative for: Foodie Groups',
                'ambiance_tags' => 'Innovative,Trendy,Asian Fusion',
                'website_url' => 'https://leerestaurant.com/',
                'phone_number' => '(416) 504-7867',
            ],
            [
                'name' => 'The Permit Room (Indian)',
                'address' => '206 Ossington Ave, Toronto, ON M6J 2Z8',
                'latitude' => 43.6480,
                'longitude' => -79.4180,
                'cuisine_type' => 'Indian',
                'description_snippet' => 'Vibrant Indian restaurant and cocktail bar with a lively atmosphere.',
                'budget_tag' => '$$',
                'budget_display_text' => '$35-60',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Spicy for: Enthusiastic Groups',
                'ambiance_tags' => 'Vibrant,Indian,Lively',
                'website_url' => 'https://thepermitroom.com/',
                'phone_number' => '(416) 551-7890',
            ],
            [
                'name' => 'Private Chef at Casa Loma',
                'address' => '1 Austin Terrace, Toronto, ON M5R 1X8',
                'latitude' => 43.6780,
                'longitude' => -79.4094,
                'cuisine_type' => 'Contemporary Canadian',
                'description_snippet' => 'Exclusive private dining experience in a castle setting with personal chef and sommelier for large groups.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$300-500 per person',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Spectacular for: Corporate Events & Celebrations',
                'ambiance_tags' => 'Luxury,Exclusive,Historic,Castle',
                'website_url' => 'https://casaloma.ca/',
                'booking_url' => 'https://casaloma.ca/private-events/',
                'phone_number' => '(416) 923-1171',
            ],
            
            [
                'name' => 'Canoe Restaurant Private Dining',
                'address' => '66 Wellington St W, 54th Floor, Toronto, ON M5K 1H6',
                'latitude' => 43.6481,
                'longitude' => -79.3808,
                'cuisine_type' => 'Contemporary Canadian',
                'description_snippet' => 'Entire restaurant buyout with panoramic city views, custom menu, and premium wine service.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$400-600 per person',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Breathtaking for: VIP Group Events',
                'ambiance_tags' => 'Luxury,Panoramic Views,Fine Dining,Exclusive',
                'website_url' => 'https://oliverbonacini.com/canoe',
                'booking_url' => 'https://oliverbonacini.com/canoe/private-dining/',
                'phone_number' => '(416) 364-0054',
            ],
            
            [
                'name' => 'CN Tower 360 Restaurant Buyout',
                'address' => '290 Bremner Blvd, Toronto, ON M5V 3L9',
                'latitude' => 43.6426,
                'longitude' => -79.3871,
                'cuisine_type' => 'International Fine Dining',
                'description_snippet' => 'Revolving restaurant with 360-degree city views, exclusive group bookings with chef\'s tasting menu.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$350-550 per person',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Iconic for: Once-in-a-Lifetime Events',
                'ambiance_tags' => 'Iconic,Revolving,Panoramic,Luxury',
                'website_url' => 'https://cntower.ca/360-restaurant',
                'booking_url' => 'https://cntower.ca/360-restaurant/private-events/',
                'phone_number' => '(416) 362-5411',
            ],
            
            // Medium Energy + $$$$$ + Large Group
            [
                'name' => 'The Hairy Tarantula Private Events',
                'address' => '2179 Bloor St W, Toronto, ON M6S 1N2',
                'latitude' => 43.6520,
                'longitude' => -79.4758,
                'cuisine_type' => 'Gastropub',
                'description_snippet' => 'Entire venue buyout with custom menu, premium bar service, and entertainment setup for large groups.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$200-350 per person',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Relaxed for: Corporate Gatherings',
                'ambiance_tags' => 'Gastropub,Private,Relaxed,Catering',
                'website_url' => 'https://hairytarantula.com/',
                'booking_url' => 'https://hairytarantula.com/private-events/',
                'phone_number' => '(416) 531-9672',
            ],
            
            [
                'name' => 'One Restaurant Private Dining Room',
                'address' => '116 Yorkville Ave, Toronto, ON M5R 1C2',
                'latitude' => 43.6706,
                'longitude' => -79.3907,
                'cuisine_type' => 'Contemporary International',
                'description_snippet' => 'Elegant private dining room with personalized service, wine pairings, and custom menu for groups.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$250-400 per person',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Sophisticated for: Business Dinners',
                'ambiance_tags' => 'Elegant,Private Dining,Yorkville,Wine',
                'website_url' => 'https://onerestaurant.ca/',
                'booking_url' => 'https://onerestaurant.ca/private-dining/',
                'phone_number' => '(416) 961-9600',
            ],
            
            // Low Energy + $$$$$ + Large Group
            [
                'name' => 'Langdon Hall Private Dining Experience',
                'address' => 'R.R. #33, Cambridge, ON N3H 4R8 (Private Transport Included)',
                'latitude' => 43.2609,
                'longitude' => -80.3144,
                'cuisine_type' => 'French Fine Dining',
                'description_snippet' => 'Relais & Châteaux property offering exclusive group dining with Michelin-level cuisine and wine cellar tours.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$500-800 per person',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Exquisite for: Luxury Retreats',
                'ambiance_tags' => 'Relais & Châteaux,Country Estate,Wine Cellar,Ultra-Luxury',
                'website_url' => 'https://langdonhall.ca/',
                'booking_url' => 'https://langdonhall.ca/private-dining/',
                'phone_number' => '(519) 740-2200',
            ],
            
            // High Energy + $$$$ + Large Group
            [
                'name' => 'Rebel Nightclub VIP Dining',
                'address' => '11 Polson St, Toronto, ON M5A 1A4',
                'latitude' => 43.6425,
                'longitude' => -79.3510,
                'cuisine_type' => 'Contemporary Fusion',
                'description_snippet' => 'VIP dining experience with premium bottle service, DJ entertainment, and custom party menu for large groups.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$150-250 per person',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Electric for: Party Groups',
                'ambiance_tags' => 'Nightclub,VIP,Bottle Service,Party Atmosphere',
                'website_url' => 'https://rebeltoronto.com/',
                'booking_url' => 'https://rebeltoronto.com/vip-dining/',
                'phone_number' => '(647) 408-7777',
            ],
            
            [
                'name' => 'Toybox Nightclub Restaurant',
                'address' => '471 Adelaide St W, Toronto, ON M5V 1T1',
                'latitude' => 43.6465,
                'longitude' => -79.3943,
                'cuisine_type' => 'Modern International',
                'description_snippet' => 'High-energy dining with live DJ, bottle service, and premium menu designed for large group celebrations.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$120-200 per person',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Vibrant for: Group Celebrations',
                'ambiance_tags' => 'Nightclub,Live Music,Bottle Service,Party',
                'website_url' => 'https://toyboxto.com/',
                'booking_url' => 'https://toyboxto.com/group-dining/',
                'phone_number' => '(647) 348-7000',
            ],
            
            // Medium Energy + $$$$ + Large Group
            [
                'name' => 'Liberty Grand Entertainment Complex',
                'address' => '25 British Columbia Rd, Toronto, ON M6K 3C3',
                'latitude' => 43.6378,
                'longitude' => -79.4172,
                'cuisine_type' => 'Contemporary Canadian',
                'description_snippet' => 'Historic venue with multiple dining rooms, custom catering, and entertainment options for large group events.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$100-180 per person',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Grand for: Corporate Events',
                'ambiance_tags' => 'Historic,Grand Ballroom,Catering,Events',
                'website_url' => 'https://libertygrand.com/',
                'booking_url' => 'https://libertygrand.com/group-dining/',
                'phone_number' => '(416) 260-5462',
            ],
            
            [
                'name' => 'Evergreen Brick Works Restaurant',
                'address' => '550 Bayview Ave, Toronto, ON M4W 3X8',
                'latitude' => 43.6865,
                'longitude' => -79.3654,
                'cuisine_type' => 'Farm-to-Table',
                'description_snippet' => 'Sustainable dining in a restored heritage building with custom group menus and nature-focused experience.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$90-150 per person',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Eco-conscious for: Team Retreats',
                'ambiance_tags' => 'Sustainable,Heritage,Nature,Farm-to-Table',
                'website_url' => 'https://evergreen.ca/',
                'booking_url' => 'https://evergreen.ca/private-dining/',
                'phone_number' => '(416) 596-7670',
            ],
            
            // Low Energy + $$$$ + Large Group
            [
                'name' => 'Auberge du Pommier Private Dining',
                'address' => '4150 Yonge St, North York, ON M2P 2C6',
                'latitude' => 43.7423,
                'longitude' => -79.4005,
                'cuisine_type' => 'French',
                'description_snippet' => 'Elegant French dining in a charming house setting with private rooms and personalized service for groups.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$120-200 per person',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Refined for: Intimate Group Gatherings',
                'ambiance_tags' => 'French,Elegant,Private Rooms,Charming',
                'website_url' => 'https://oliverbonacini.com/aubergedupommier',
                'booking_url' => 'https://oliverbonacini.com/aubergedupommier/private-dining/',
                'phone_number' => '(416) 222-2220',
            ],
            
            // High Energy + $$$ + Large Group
            [
                'name' => 'Real Sports Bar & Grill Group Section',
                'address' => '15 York St, Toronto, ON M5J 0A3',
                'latitude' => 43.6434,
                'longitude' => -79.3791,
                'cuisine_type' => 'Sports Bar & Grill',
                'description_snippet' => 'Massive sports bar with dedicated group sections, big screens, and party packages for large groups.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$60-100 per person',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Energetic for: Sports Fan Groups',
                'ambiance_tags' => 'Sports Bar,Big Screens,Lively,Group Packages',
                'website_url' => 'https://realsports.ca/',
                'booking_url' => 'https://realsports.ca/group-bookings/',
                'phone_number' => '(416) 815-7325',
            ],
            
            [
                'name' => 'Duke of York Pub Large Group Dining',
                'address' => '39 Prince Arthur Ave, Toronto, ON M5R 1B2',
                'latitude' => 43.6706,
                'longitude' => -79.3907,
                'cuisine_type' => 'British Pub',
                'description_snippet' => 'Traditional British pub with group reservation areas, live music, and hearty pub fare for large parties.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$50-80 per person',
                'energy_tag' => 'High',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Lively for: Casual Group Gatherings',
                'ambiance_tags' => 'British Pub,Live Music,Traditional,Group Areas',
                'website_url' => 'https://dukeofyorktoronto.com/',
                'booking_url' => 'https://dukeofyorktoronto.com/group-reservations/',
                'phone_number' => '(416) 964-2441',
            ],
            
            // Medium Energy + $$$ + Large Group
            [
                'name' => 'Casa Madera Group Dining',
                'address' => '550 Wellington St W, Toronto, ON M5V 2V4',
                'latitude' => 43.6416,
                'longitude' => -79.3980,
                'cuisine_type' => 'Mexican/Mediterranean',
                'description_snippet' => 'Vibrant atmosphere with group dining packages, shared plates, and celebration options for large parties.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$70-120 per person',
                'energy_tag' => 'Medium',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Festive for: Group Celebrations',
                'ambiance_tags' => 'Vibrant,Mexican,Shared Plates,Celebration',
                'website_url' => 'https://www.casamadera.com/toronto',
                'booking_url' => 'https://www.casamadera.com/toronto/group-dining',
                'phone_number' => '(416) 300-3333',
            ],
            
            // Low Energy + $$$ + Large Group
            [
                'name' => 'Hart House Restaurant Group Dining',
                'address' => '7 Hart House Circle, Toronto, ON M5S 3H3',
                'latitude' => 43.6628,
                'longitude' => -79.3957,
                'cuisine_type' => 'Contemporary Canadian',
                'description_snippet' => 'Historic university setting with elegant group dining rooms and refined Canadian cuisine for large parties.',
                'budget_tag' => '$$$',
                'budget_display_text' => '$60-90 per person',
                'energy_tag' => 'Low',
                'people_tag' => 'Large Group',
                'people_display_text' => 'Elegant for: Academic & Cultural Groups',
                'ambiance_tags' => 'Historic,University,Elegant,Cultural',
                'website_url' => 'https://harthouse.ca/',
                'booking_url' => 'https://harthouse.ca/dining/group-dining/',
                'phone_number' => '(416) 978-2445',
            ],
            // Low-$$$$-Solo
[
    'name' => 'Omakase Sushi Counter at Yukashi',
    'address' => '122 Elizabeth St, Toronto, ON M5G 1P5',
    'latitude' => 43.6565,
    'longitude' => -79.3799,
    'cuisine_type' => 'Japanese Omakase',
    'description_snippet' => 'Intimate 8-seat sushi counter offering premium omakase experience perfect for solo fine dining.',
    'budget_tag' => '$$$$',
    'budget_display_text' => '$180-250 per person',
    'energy_tag' => 'Low',
    'people_tag' => 'Solo',
    'people_display_text' => 'Contemplative for: Solo Sushi Connoisseurs',
    'ambiance_tags' => 'Omakase,Intimate,Counter Seating,Premium',
    'website_url' => 'https://yukashitoronto.com/',
    'booking_url' => 'https://yukashitoronto.com/reservations/',
    'phone_number' => '(416) 977-0008',
],

// Low-$$$$$-Solo
[
    'name' => 'Chef\'s Table at Alo',
    'address' => '163 Spadina Ave, 3rd Floor, Toronto, ON M5V 2L6',
    'latitude' => 43.6475,
    'longitude' => -79.3986,
    'cuisine_type' => 'Modern French',
    'description_snippet' => 'Exclusive chef\'s table experience at Toronto\'s premier fine dining restaurant, perfect for solo culinary journeys.',
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$350-500 per person',
    'energy_tag' => 'Low',
    'people_tag' => 'Solo',
    'people_display_text' => 'Exquisite for: Solo Fine Dining Enthusiasts',
    'ambiance_tags' => 'Michelin-level,Chef\'s Table,Exclusive,Modern French',
    'website_url' => 'https://alorestaurant.com/',
    'booking_url' => 'https://alorestaurant.com/reservations/',
    'phone_number' => '(416) 260-2222',
],

// Low-$$$$-Date
[
    'name' => 'Sotto Sotto Romantic Dining',
    'address' => '120 Avenue Rd, Toronto, ON M5R 2H4',
    'latitude' => 43.6706,
    'longitude' => -79.3907,
    'cuisine_type' => 'Northern Italian',
    'description_snippet' => 'Intimate Northern Italian restaurant with cozy alcoves, perfect for romantic fine dining dates.',
    'budget_tag' => '$$$$',
    'budget_display_text' => '$120-180 per person',
    'energy_tag' => 'Low',
    'people_tag' => 'Date',
    'people_display_text' => 'Romantic for: Intimate Date Nights',
    'ambiance_tags' => 'Romantic,Italian,Intimate,Cozy Alcoves',
    'website_url' => 'https://sottosotto.ca/',
    'booking_url' => 'https://sottosotto.ca/reservations/',
    'phone_number' => '(416) 962-0011',
],

// Low-$$$$$-Date
[
    'name' => 'Private Dining at Canoe',
    'address' => '66 Wellington St W, 54th Floor, Toronto, ON M5K 1H6',
    'latitude' => 43.6481,
    'longitude' => -79.3808,
    'cuisine_type' => 'Contemporary Canadian',
    'description_snippet' => 'Private corner table with panoramic city views and personalized chef\'s menu for ultimate romantic dining.',
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$400-600 per couple',
    'energy_tag' => 'Low',
    'people_tag' => 'Date',
    'people_display_text' => 'Breathtaking for: Special Anniversary Dates',
    'ambiance_tags' => 'Private,Panoramic Views,Anniversary,Ultra-Romantic',
    'website_url' => 'https://oliverbonacini.com/canoe',
    'booking_url' => 'https://oliverbonacini.com/canoe/private-dining/',
    'phone_number' => '(416) 364-0054',
],

// Low-$$-Large Group
[
    'name' => 'Sunset Grill Group Seating',
    'address' => '2006 Yonge St, Toronto, ON M4S 1Z9',
    'latitude' => 43.7089,
    'longitude' => -79.3957,
    'cuisine_type' => 'Canadian Comfort',
    'description_snippet' => 'Family restaurant with large booth sections and group menus, perfect for relaxed large group dining.',
    'budget_tag' => '$$',
    'budget_display_text' => '$25-40 per person',
    'energy_tag' => 'Low',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Comfortable for: Family Reunions',
    'ambiance_tags' => 'Family-Friendly,Comfortable,Large Booths,Casual',
    'website_url' => 'https://sunsetgrill.ca/',
    'booking_url' => 'https://sunsetgrill.ca/group-reservations/',
    'phone_number' => '(416) 489-7291',
],

// Low-$$$-Small Group
[
    'name' => 'Rasa Wine Bar',
    'address' => '196 Robert St, Toronto, ON M5S 2K7',
    'latitude' => 43.6666,
    'longitude' => -79.4034,
    'cuisine_type' => 'Modern Canadian',
    'description_snippet' => 'Intimate wine bar with curated small plates and extensive wine list, perfect for sophisticated small groups.',
    'budget_tag' => '$$$',
    'budget_display_text' => '$60-90 per person',
    'energy_tag' => 'Low',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Sophisticated for: Wine Enthusiast Groups',
    'ambiance_tags' => 'Wine Bar,Intimate,Small Plates,Sophisticated',
    'website_url' => 'https://rasatoronto.com/',
    'booking_url' => 'https://rasatoronto.com/reservations/',
    'phone_number' => '(647) 345-8121',
],

// Low-$$$-Large Group
[
    'name' => 'Buca King West Group Dining',
    'address' => '604 King St W, Toronto, ON M5V 1M6',
    'latitude' => 43.6441,
    'longitude' => -79.3965,
    'cuisine_type' => 'Italian',
    'description_snippet' => 'Spacious Italian restaurant with group dining areas and family-style sharing menus for large parties.',
    'budget_tag' => '$$$',
    'budget_display_text' => '$50-80 per person',
    'energy_tag' => 'Low',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Welcoming for: Italian Family Gatherings',
    'ambiance_tags' => 'Italian,Family-Style,Spacious,Group Areas',
    'website_url' => 'https://www.buca.ca/',
    'booking_url' => 'https://www.buca.ca/group-dining/',
    'phone_number' => '(416) 865-1600',
],

// MEDIUM ENERGY MISSING COMBINATIONS

// Medium-$-Solo
[
    'name' => 'Ramen Isshin Counter Seating',
    'address' => '421 Dundas St W, Toronto, ON M5T 1G6',
    'latitude' => 43.6552,
    'longitude' => -79.3965,
    'cuisine_type' => 'Japanese Ramen',
    'description_snippet' => 'Authentic ramen shop with counter seating, perfect for solo diners seeking quality Japanese comfort food.',
    'budget_tag' => '$',
    'budget_display_text' => '$12-18 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Solo',
    'people_display_text' => 'Authentic for: Solo Ramen Lovers',
    'ambiance_tags' => 'Authentic,Counter Seating,Japanese,Quick Service',
    'website_url' => 'https://ramenisshin.com/',
    'phone_number' => '(416) 928-3292',
],

// Medium-$-Date
[
    'name' => 'Kensington Market Food Tour',
    'address' => 'Various Vendors, Kensington Market, Toronto, ON',
    'latitude' => 43.6548,
    'longitude' => -79.3999,
    'cuisine_type' => 'International Street Food',
    'description_snippet' => 'Casual food tour through diverse market vendors, perfect for adventurous couples on a budget.',
    'budget_tag' => '$',
    'budget_display_text' => '$15-25 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Date',
    'people_display_text' => 'Adventurous for: Foodie Couples',
    'ambiance_tags' => 'Market,Diverse,Street Food,Casual Adventure',
    'website_url' => 'https://kensington-market.ca/',
],

// Medium-$-Small Group
[
    'name' => 'Guu Izakaya',
    'address' => '398 Church St, Toronto, ON M5B 2A2',
    'latitude' => 43.6584,
    'longitude' => -79.3759,
    'cuisine_type' => 'Japanese Izakaya',
    'description_snippet' => 'Lively Japanese pub with shared plates and sake, perfect for small groups seeking authentic izakaya experience.',
    'budget_tag' => '$',
    'budget_display_text' => '$18-30 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Social for: Friend Groups',
    'ambiance_tags' => 'Izakaya,Lively,Shared Plates,Sake',
    'website_url' => 'https://guu-izakaya.com/',
    'phone_number' => '(416) 323-2339',
],

// Medium-$-Large Group
[
    'name' => 'All You Can Eat Korean BBQ',
    'address' => '5734 Yonge St, North York, ON M2M 4E7',
    'latitude' => 43.7845,
    'longitude' => -79.4087,
    'cuisine_type' => 'Korean BBQ',
    'description_snippet' => 'All-you-can-eat Korean BBQ with large tables perfect for groups wanting to cook and share together.',
    'budget_tag' => '$',
    'budget_display_text' => '$20-35 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Interactive for: Group Cooking Experience',
    'ambiance_tags' => 'AYCE,Korean BBQ,Interactive,Group Tables',
    'website_url' => 'https://koreanbbqtoronto.com/',
    'phone_number' => '(416) 733-2992',
],

// Medium-$$-Date
[
    'name' => 'Cluny Bistro',
    'address' => '35 Tank House Ln, Toronto, ON M5A 3C4',
    'latitude' => 43.6508,
    'longitude' => -79.3592,
    'cuisine_type' => 'French Bistro',
    'description_snippet' => 'Charming French bistro in Distillery District with intimate atmosphere perfect for romantic dates.',
    'budget_tag' => '$$',
    'budget_display_text' => '$35-55 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Date',
    'people_display_text' => 'Charming for: Romantic Bistro Dates',
    'ambiance_tags' => 'French Bistro,Romantic,Distillery District,Charming',
    'website_url' => 'https://cluny.ca/',
    'booking_url' => 'https://cluny.ca/reservations/',
    'phone_number' => '(416) 203-2632',
],

// Medium-$$$$-Small Group
[
    'name' => 'Edulis Private Table',
    'address' => '169 Niagara St, Toronto, ON M5V 1C9',
    'latitude' => 43.6416,
    'longitude' => -79.4030,
    'cuisine_type' => 'Mediterranean',
    'description_snippet' => 'Intimate Mediterranean restaurant with chef\'s table experience for small groups seeking refined dining.',
    'budget_tag' => '$$$$',
    'budget_display_text' => '$100-150 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Refined for: Culinary Enthusiast Groups',
    'ambiance_tags' => 'Mediterranean,Chef\'s Table,Intimate,Refined',
    'website_url' => 'https://edulis.ca/',
    'booking_url' => 'https://edulis.ca/reservations/',
    'phone_number' => '(416) 924-4900',
],

// Medium-$$$$$-Date
[
    'name' => 'Helicopter Dinner Experience',
    'address' => 'Billy Bishop Airport, Toronto, ON M5V 1A1',
    'latitude' => 43.6275,
    'longitude' => -79.3963,
    'cuisine_type' => 'Sky Dining Experience',
    'description_snippet' => 'Helicopter tour followed by exclusive rooftop dining with panoramic city views for ultimate romantic experience.',
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$800-1200 per couple',
    'energy_tag' => 'Medium',
    'people_tag' => 'Date',
    'people_display_text' => 'Unforgettable for: Proposal Dinners',
    'ambiance_tags' => 'Helicopter,Rooftop,Panoramic,Once-in-a-Lifetime',
    'website_url' => 'https://torontohelicopterdining.com/',
    'booking_url' => 'https://torontohelicopterdining.com/reservations/',
    'phone_number' => '(416) 203-7777',
],

// Medium-$$$$$-Small Group
[
    'name' => 'Private Chef at Aga Khan Museum',
    'address' => '77 Wynford Dr, Toronto, ON M3C 1K1',
    'latitude' => 43.7253,
    'longitude' => -79.3327,
    'cuisine_type' => 'Contemporary International',
    'description_snippet' => 'Private chef experience in museum setting with custom menu and cultural tours for sophisticated small groups.',
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$300-500 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Cultural for: Refined Small Groups',
    'ambiance_tags' => 'Museum,Private Chef,Cultural,Exclusive',
    'website_url' => 'https://www.agakhanmuseum.org/',
    'booking_url' => 'https://www.agakhanmuseum.org/private-dining/',
    'phone_number' => '(416) 646-4677',
],

// Medium-$$$$-Solo
[
    'name' => 'Sushi Kaji Omakase Bar',
    'address' => '860 The Queensway, Etobicoke, ON M8Z 1N5',
    'latitude' => 43.6167,
    'longitude' => -79.5019,
    'cuisine_type' => 'Japanese Omakase',
    'description_snippet' => 'Renowned omakase sushi bar with counter seating, perfect for solo sushi connoisseurs seeking authenticity.',
    'budget_tag' => '$$$$',
    'budget_display_text' => '$200-300 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Solo',
    'people_display_text' => 'Authentic for: Sushi Purists',
    'ambiance_tags' => 'Omakase,Authentic,Counter Seating,Renowned',
    'website_url' => 'https://sushikaji.com/',
    'booking_url' => 'https://sushikaji.com/reservations/',
    'phone_number' => '(416) 252-2166',
],

// HIGH ENERGY MISSING COMBINATIONS

// High-$-Solo
[
    'name' => 'Sports Bar Counter at Real Sports',
    'address' => '15 York St, Toronto, ON M5J 0A3',
    'latitude' => 43.6434,
    'longitude' => -79.3791,
    'cuisine_type' => 'Sports Bar',
    'description_snippet' => 'High-energy sports bar with counter seating facing big screens, perfect for solo sports fans.',
    'budget_tag' => '$',
    'budget_display_text' => '$15-25 per person',
    'energy_tag' => 'High',
    'people_tag' => 'Solo',
    'people_display_text' => 'Energetic for: Solo Sports Fans',
    'ambiance_tags' => 'Sports Bar,Big Screens,Counter Seating,High Energy',
    'website_url' => 'https://realsports.ca/',
    'phone_number' => '(416) 815-7325',
],

// High-$-Date
[
    'name' => 'Karaoke Box Date Night',
    'address' => '346 Spadina Ave, Toronto, ON M5T 2G3',
    'latitude' => 43.6548,
    'longitude' => -79.3999,
    'cuisine_type' => 'Korean Karaoke & Snacks',
    'description_snippet' => 'Private karaoke rooms with Korean snacks and drinks, perfect for fun, energetic date nights.',
    'budget_tag' => '$',
    'budget_display_text' => '$20-35 per couple',
    'energy_tag' => 'High',
    'people_tag' => 'Date',
    'people_display_text' => 'Fun for: Playful Couples',
    'ambiance_tags' => 'Karaoke,Private Rooms,Korean,Fun',
    'website_url' => 'https://karaokeboxto.com/',
    'booking_url' => 'https://karaokeboxto.com/reservations/',
    'phone_number' => '(416) 599-7799',
],

// High-$-Small Group
[
    'name' => 'Trivia Night at The Pint',
    'address' => '277 Front St W, Toronto, ON M5V 2X4',
    'latitude' => 43.6433,
    'longitude' => -79.3871,
    'cuisine_type' => 'Pub Food',
    'description_snippet' => 'Lively pub with trivia nights and group tables, perfect for competitive small groups on a budget.',
    'budget_tag' => '$',
    'budget_display_text' => '$18-30 per person',
    'energy_tag' => 'High',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Competitive for: Trivia Teams',
    'ambiance_tags' => 'Pub,Trivia Night,Competitive,Group Tables',
    'website_url' => 'https://thepint.ca/',
    'phone_number' => '(647) 347-7468',
],

// High-$$$-Solo
[
    'name' => 'Sushi Bar at Miku',
    'address' => '10 Bay St, Toronto, ON M5J 2R8',
    'latitude' => 43.6426,
    'longitude' => -79.3771,
    'cuisine_type' => 'Japanese Aburi Sushi',
    'description_snippet' => 'Dynamic sushi bar with flame-seared aburi preparation, perfect for solo diners seeking culinary theater.',
    'budget_tag' => '$$$',
    'budget_display_text' => '$60-90 per person',
    'energy_tag' => 'High',
    'people_tag' => 'Solo',
    'people_display_text' => 'Dynamic for: Solo Culinary Adventurers',
    'ambiance_tags' => 'Aburi Sushi,Culinary Theater,Sushi Bar,Dynamic',
    'website_url' => 'https://mikutoronto.com/',
    'booking_url' => 'https://mikutoronto.com/reservations/',
    'phone_number' => '(647) 347-7347',
],

// High-$$$$$-Small Group
[
    'name' => 'Private Racing Simulator & Dining',
    'address' => 'Downtown Toronto (Private Location)',
    'latitude' => 43.6532,
    'longitude' => -79.3832,
    'cuisine_type' => 'Experiential Dining',
    'description_snippet' => 'Exclusive racing simulator experience with premium catering and champagne service for thrill-seeking groups.',
    'budget_tag' => '$$$$$',
    'budget_display_text' => '$500-800 per person',
    'energy_tag' => 'High',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Thrilling for: Adrenaline Seekers',
    'ambiance_tags' => 'Racing Simulator,Exclusive,Premium,Adrenaline',
    'website_url' => 'https://torontoracing.com/',
    'booking_url' => 'https://torontoracing.com/private-experiences/',
    'phone_number' => '(416) 888-RACE',
],

[
    'name' => 'Harriets Rooftop',
                'address' => '550 Wellington St W Suite C, Toronto, Ontario M5V 2V4',
                'latitude' => 43.6457,
                'longitude' => -79.4003,
                'cuisine_type' => 'Japanese',
                'description_snippet' => 'Light bites made from seasonal ingredients, as well as wellness cocktails prepared with fresh juices',
                'budget_tag' => '$$',
                'budget_display_text' => '$25-50',
                'energy_tag' => 'Low',
                'people_tag' => 'Date',
                'people_display_text' => 'Social for: Date',
                'ambiance_tags' => 'Casual,Quick,Japanese',
                'website_url' => 'https://www.1hotels.com/toronto/taste/harriets-rooftop?utm_source=google-gbp&utm_medium=organic&utm_campaign=gbpmenu#menu',
                'phone_number' => '(416) 601-3599',
    
],
[
    'name' => 'Benares',
    'address' => '49 Front St E Suite 001, Toronto, Ontario M5E 1B3',
    'latitude' => 43.6493,
    'longitude' => -79.3766,
    'cuisine_type' => 'Indian',
    'description_snippet' => 'Best Indian Restaurant in Toronto serving Authentic Indian food with an Indian inspired ambience in the heart of downtown Toronto.',
    'budget_tag' => '$$$',
    'budget_display_text' => '$30-45',
    'energy_tag' => 'Medium',
    'people_tag' => 'Small Group',
    'people_display_text' => 'Social for: Friend Groups',
    'ambiance_tags' => 'Indian',
    'website_url' => 'https://benares.ca/',
    'phone_number' => '(416) 955-9000',
],

[
'name' => 'Banh Mi Boys',
    'address' => '392 Queen St W, Toronto, Ontario M5V 2A6',
    'latitude' => 43.6489,
    'longitude' => -79.3961,
    'cuisine_type' => 'Vietnamese',
    'description_snippet' => 'juicy hot meats nestled in crispy baguettes.',
    'budget_tag' => '$',
    'budget_display_text' => '$5-10',
    'energy_tag' => 'Low',
    'people_tag' => 'Solo',
    'people_display_text' => 'Perfect for: Solo',
    'ambiance_tags' => 'Vietnamese',
    'website_url' => 'https://banhmiboys.com/',
    'phone_number' => '(416) 733-2992',
],
[
    'name' => 'Jacobs & Co. Steakhouse',
    'address' => '12 Brant St Level Four, Toronto, Ontario M5V 2M1',
    'latitude' => 43.6457,
    'longitude' => -79.3982,
    'cuisine_type' => 'American',
    'description_snippet' => 'It continues to honour its legacy with exceptional steaks, signature dry-aging, and refined yet genuine hospitality.',
    'budget_tag' => '$$$',
    'budget_display_text' => '$50-100',
    'energy_tag' => 'Medium',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Perfect for: Large group',
    'ambiance_tags' => 'American',
    'website_url' => 'https://www.jacobssteakhouse.com/',
    'phone_number' => '(416) 366-0200',

],
[
    'name' => 'Sunset Grill Toronto',
    'address' => '1 Richmond St W Yonge St, Toronto, Ontario M5H 3W4 ',
    'latitude' => 43.6494,
    'longitude' => -79.3817,
    'cuisine_type' => 'Grill',
    'description_snippet' => 'Looking for the perfect spot to bring the family for some fresh-made breakfast or to catch up with old friends over brunch.',
    'budget_tag' => '$$',
    'budget_display_text' => '$10-20',
    'energy_tag' => 'High',
    'people_tag' => 'Date',
    'people_display_text' => 'Perfect for: Date',
    'ambiance_tags' => 'Grill',
    'website_url' => 'https://sunsetgrill.ca/food/all-day-breakfast/',
    'phone_number' => '(905) 829-1142',
],
[
    'name' => 'BeaverTails',
    'address' => '145 Queens Quay W Pier 6, Toronto, Ontario M5J 2H4',
    'latitude' => 43.6406,
    'longitude' => -79.3803,
    'cuisine_type' => 'Dessert',
    'description_snippet' => 'Iconic Canadian fried pastries with decadent toppings, as well as snacks like poutine, fries, hot dogs, and ice cream.',
    'budget_tag' => '$',
    'budget_display_text' => '$10-30 per person',
    'energy_tag' => 'Medium',
    'people_tag' => 'Large Group',
    'people_display_text' => 'Perfect for: Large Group',
    'ambiance_tags' => 'Dessert',
    'website_url' => 'https://beavertails.com/',
    'phone_number' => '(416) 360-8245',
],
[
    'name' => 'Volos Greek Cuisine',
    'address' => '133 Richmond St W, Toronto, ON M5H 2L3',
    'latitude' => 43.6406,
    'longitude' => -79.3785,
    'cuisine_type' => 'Seafood',
    'description_snippet' => 'Fresh, healthy flavours and emphasis on beautiful presentation please both the appetite and eyes at Volos.',
    'budget_tag' => '$$$',
    'budget_display_text' => '$35-50',
    'energy_tag' => 'Low',
    'people_tag' => 'Date',
    'people_display_text' => 'Perfect for: Date',
    'ambiance_tags' => 'Seafood',
    'website_url' => 'https://www.volos.ca/',
    'booking_url' => 'https://www.volos.ca/reservations',
    'phone_number' => '(416) 861-1211',
],
[
    'name' => 'Hys Steakhouse & Cocktail Bar',
                'address' => '365 Bay St., Toronto, ON M5H 2V1',
                'latitude' => 43.6509,
                'longitude' => -79.3811,
                'cuisine_type' => 'Steak House',
                'description_snippet' => ' Hys offers guests the finest Canadian Prime beef, fresh seafood and delicoius takes on traditional steakhouse cuisine.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$70-120',
                'energy_tag' => 'Medium',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Festive for: Small Group',
                'ambiance_tags' => 'Steak House',
                'website_url' => 'https://www.hyssteakhouse.com/',
                'booking_url' => 'https://www.hyssteakhouse.com/menus/toronto',
                'phone_number' => '(416) 364-6600',

],
[
    'name' => 'Canoe',
                'address' => '66 Wellington St W 54th floor, Toronto, ON M5K 1H6',
                'latitude' => 43.6454,
                'longitude' => -79.3808,
                'cuisine_type' => 'International',
                'description_snippet' => 'Connecting people to place through contemporary Canadian cuisine, Canoe crafts inspired dishes reflective of our country’s diverse landscape.',
                'budget_tag' => '$$$$',
                'budget_display_text' => '$70-120',
                'energy_tag' => 'High',
                'people_tag' => 'Solo',
                'people_display_text' => 'Perfect for: Solo',
                'ambiance_tags' => 'City Views',
                'website_url' => 'https://www.canoerestaurant.com/',
                'booking_url' => 'https://www.canoerestaurant.com/menus/',
                'phone_number' => '(416) 364-0054',
],
[
    'name' => 'Ruths Chris Steak House',
                'address' => '145 Richmond Street Hilton Toronto, Toronto, Ontario M5H 2L2',
                'latitude' => 43.6489,
                'longitude' => -79.3834,
                'cuisine_type' => 'Steakhouse',
                'description_snippet' => 'Ruths Chris Steak House specializes in serving USDA Prime steaks, each seared to perfection, finished with butter and freshly chopped parsley, and served sizzling on a 500-degree plate.',
                'budget_tag' => '$$$$$',
                'budget_display_text' => '$100-120',
                'energy_tag' => 'High',
                'people_tag' => 'Small Group',
                'people_display_text' => 'Perfect for: Small Group',
                'ambiance_tags' => 'Steakhouse',
                'website_url' => 'https://ruthschris.ca/',
                'booking_url' => 'https://ruthschris.ca/menus/dinner-menu/',
                'phone_number' => '(416) 364-0054',
],

        ];

        foreach ($restaurants as $restaurant) {
            Restaurant::create($restaurant);
        }
    }
}